//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using DslModeling = global::Microsoft.VisualStudio.Modeling;
using DslDesign = global::Microsoft.VisualStudio.Modeling.Design;
namespace UPM_IPS.XCYLSProyectoIPS
{
	/// <summary>
	/// DomainClass DeraWebIPS
	/// The root in which all other elements are embedded. Appears as a diagram.
	/// </summary>
	[DslDesign::DisplayNameResource("UPM_IPS.XCYLSProyectoIPS.DeraWebIPS.DisplayName", typeof(global::UPM_IPS.XCYLSProyectoIPS.XCYLSProyectoIPSDomainModel), "UPM_IPS.XCYLSProyectoIPS.GeneratedCode.DomainModelResx")]
	[DslDesign::DescriptionResource("UPM_IPS.XCYLSProyectoIPS.DeraWebIPS.Description", typeof(global::UPM_IPS.XCYLSProyectoIPS.XCYLSProyectoIPSDomainModel), "UPM_IPS.XCYLSProyectoIPS.GeneratedCode.DomainModelResx")]
	[DslModeling::DomainModelOwner(typeof(global::UPM_IPS.XCYLSProyectoIPS.XCYLSProyectoIPSDomainModel))]
	[global::System.CLSCompliant(true)]
	[DslModeling::DomainObjectId("c1d6649a-daef-493e-a618-d1b033cba6f0")]
	public partial class DeraWebIPS : DslModeling::ModelElement
	{
		#region Constructors, domain class Id
	
		/// <summary>
		/// DeraWebIPS domain class Id.
		/// </summary>
		public static readonly new global::System.Guid DomainClassId = new global::System.Guid(0xc1d6649a, 0xdaef, 0x493e, 0xa6, 0x18, 0xd1, 0xb0, 0x33, 0xcb, 0xa6, 0xf0);
		/// <summary>
		/// Constructor
		/// </summary>
		/// <param name="store">Store where new element is to be created.</param>
		/// <param name="propertyAssignments">List of domain property id/value pairs to set once the element is created.</param>
		public DeraWebIPS(DslModeling::Store store, params DslModeling::PropertyAssignment[] propertyAssignments)
			: this(store != null ? store.DefaultPartitionForClass(DomainClassId) : null, propertyAssignments)
		{
		}
		
		/// <summary>
		/// Constructor
		/// </summary>
		/// <param name="partition">Partition where new element is to be created.</param>
		/// <param name="propertyAssignments">List of domain property id/value pairs to set once the element is created.</param>
		public DeraWebIPS(DslModeling::Partition partition, params DslModeling::PropertyAssignment[] propertyAssignments)
			: base(partition, propertyAssignments)
		{
		}
		#endregion
		#region Entidad opposite domain role accessor
		
		/// <summary>
		/// Gets a list of Entidad.
		/// Description for UPM_IPS.XCYLSProyectoIPS.DeraWebIPSHasEntidad.DeraWebIPS
		/// </summary>
		public virtual DslModeling::LinkedElementCollection<Entidad> Entidad
		{
			[global::System.Diagnostics.DebuggerStepThrough]
			get
			{
				return GetRoleCollection<DslModeling::LinkedElementCollection<Entidad>, Entidad>(global::UPM_IPS.XCYLSProyectoIPS.DeraWebIPSHasEntidad.DeraWebIPSDomainRoleId);
			}
		}
		#endregion
		#region Relacioned opposite domain role accessor
		
		/// <summary>
		/// Gets a list of Relacioned.
		/// Description for UPM_IPS.XCYLSProyectoIPS.DeraWebIPSHasRelacioned.DeraWebIPS
		/// </summary>
		public virtual DslModeling::LinkedElementCollection<Relacion> Relacioned
		{
			[global::System.Diagnostics.DebuggerStepThrough]
			get
			{
				return GetRoleCollection<DslModeling::LinkedElementCollection<Relacion>, Relacion>(global::UPM_IPS.XCYLSProyectoIPS.DeraWebIPSHasRelacioned.DeraWebIPSDomainRoleId);
			}
		}
		#endregion
		#region ElementGroupPrototype Merge methods
		/// <summary>
		/// Returns a value indicating whether the source element represented by the
		/// specified root ProtoElement can be added to this element.
		/// </summary>
		/// <param name="rootElement">
		/// The root ProtoElement representing a source element.  This can be null, 
		/// in which case the ElementGroupPrototype does not contain an ProtoElements
		/// and the code should inspect the ElementGroupPrototype context information.
		/// </param>
		/// <param name="elementGroupPrototype">The ElementGroupPrototype that contains the root ProtoElement.</param>
		/// <returns>true if the source element represented by the ProtoElement can be added to this target element.</returns>
		protected override bool CanMerge(DslModeling::ProtoElementBase rootElement, DslModeling::ElementGroupPrototype elementGroupPrototype)
		{
			if ( elementGroupPrototype == null ) throw new global::System.ArgumentNullException("elementGroupPrototype");
			
			if (rootElement != null)
			{
				DslModeling::DomainClassInfo rootElementDomainInfo = this.Partition.DomainDataDirectory.GetDomainClass(rootElement.DomainClassId);
				
				if (rootElementDomainInfo.IsDerivedFrom(global::UPM_IPS.XCYLSProyectoIPS.Entidad.DomainClassId)) 
				{
					return true;
				}
				
				if (rootElementDomainInfo.IsDerivedFrom(global::UPM_IPS.XCYLSProyectoIPS.Relacion.DomainClassId)) 
				{
					return true;
				}
			}
			return base.CanMerge(rootElement, elementGroupPrototype);
		}
		
		/// <summary>
		/// Called by the Merge process to create a relationship between 
		/// this target element and the specified source element. 
		/// Typically, a parent-child relationship is established
		/// between the target element (the parent) and the source element 
		/// (the child), but any relationship can be established.
		/// </summary>
		/// <param name="sourceElement">The element that is to be related to this model element.</param>
		/// <param name="elementGroup">The group of source ModelElements that have been rehydrated into the target store.</param>
		/// <remarks>
		/// This method is overriden to create the relationship between the target element and the specified source element.
		/// The base method does nothing.
		/// </remarks>
		protected override void MergeRelate(DslModeling::ModelElement sourceElement, DslModeling::ElementGroup elementGroup)
		{
			// In general, sourceElement is allowed to be null, meaning that the elementGroup must be parsed for special cases.
			// However this is not supported in generated code.  Use double-deriving on this class and then override MergeRelate completely if you 
			// need to support this case.
			if ( sourceElement == null ) throw new global::System.ArgumentNullException("sourceElement");
		
				
			global::UPM_IPS.XCYLSProyectoIPS.Entidad sourceEntidad1 = sourceElement as global::UPM_IPS.XCYLSProyectoIPS.Entidad;
			if (sourceEntidad1 != null)
			{
				// Create link for path DeraWebIPSHasEntidad.Entidad
				this.Entidad.Add(sourceEntidad1);

				return;
			}
				
			global::UPM_IPS.XCYLSProyectoIPS.Relacion sourceRelacion2 = sourceElement as global::UPM_IPS.XCYLSProyectoIPS.Relacion;
			if (sourceRelacion2 != null)
			{
				// Create link for path DeraWebIPSHasRelacioned.Relacioned
				this.Relacioned.Add(sourceRelacion2);

				return;
			}
		
			// Sdk workaround to runtime bug #879350 (DSL: can't copy and paste a MEL that has a MEX). Avoid MergeRelate on ModelElementExtension
			// during a "Paste".
			if (sourceElement is DslModeling::ExtensionElement
				&& sourceElement.Store.TransactionManager.CurrentTransaction.TopLevelTransaction.Context.ContextInfo.ContainsKey("{9DAFD42A-DC0E-4d78-8C3F-8266B2CF8B33}"))
			{
				return;
			}
		
			// Fall through to base class if this class hasn't handled the merge.
			base.MergeRelate(sourceElement, elementGroup);
		}
		
		/// <summary>
		/// Performs operation opposite to MergeRelate - i.e. disconnects a given
		/// element from the current one (removes links created by MergeRelate).
		/// </summary>
		/// <param name="sourceElement">Element to be unmerged/disconnected.</param>
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1800:DoNotCastUnnecessarily")]
		protected override void MergeDisconnect(DslModeling::ModelElement sourceElement)
		{
			if (sourceElement == null) throw new global::System.ArgumentNullException("sourceElement");
				
			global::UPM_IPS.XCYLSProyectoIPS.Entidad sourceEntidad1 = sourceElement as global::UPM_IPS.XCYLSProyectoIPS.Entidad;
			if (sourceEntidad1 != null)
			{
				// Delete link for path DeraWebIPSHasEntidad.Entidad
				
				foreach (DslModeling::ElementLink link in global::UPM_IPS.XCYLSProyectoIPS.DeraWebIPSHasEntidad.GetLinks((global::UPM_IPS.XCYLSProyectoIPS.DeraWebIPS)this, sourceEntidad1))
				{
					// Delete the link, but without possible delete propagation to the element since it's moving to a new location.
					link.Delete(global::UPM_IPS.XCYLSProyectoIPS.DeraWebIPSHasEntidad.DeraWebIPSDomainRoleId, global::UPM_IPS.XCYLSProyectoIPS.DeraWebIPSHasEntidad.EntidadDomainRoleId);
				}

				return;
			}
				
			global::UPM_IPS.XCYLSProyectoIPS.Relacion sourceRelacion2 = sourceElement as global::UPM_IPS.XCYLSProyectoIPS.Relacion;
			if (sourceRelacion2 != null)
			{
				// Delete link for path DeraWebIPSHasRelacioned.Relacioned
				
				foreach (DslModeling::ElementLink link in global::UPM_IPS.XCYLSProyectoIPS.DeraWebIPSHasRelacioned.GetLinks((global::UPM_IPS.XCYLSProyectoIPS.DeraWebIPS)this, sourceRelacion2))
				{
					// Delete the link, but without possible delete propagation to the element since it's moving to a new location.
					link.Delete(global::UPM_IPS.XCYLSProyectoIPS.DeraWebIPSHasRelacioned.DeraWebIPSDomainRoleId, global::UPM_IPS.XCYLSProyectoIPS.DeraWebIPSHasRelacioned.RelacionDomainRoleId);
				}

				return;
			}
			// Fall through to base class if this class hasn't handled the unmerge.
			base.MergeDisconnect(sourceElement);
		}
		#endregion
	}
}
namespace UPM_IPS.XCYLSProyectoIPS
{
	/// <summary>
	/// DomainClass Entidad
	/// Description for UPM_IPS.XCYLSProyectoIPS.Entidad
	/// </summary>
	[DslDesign::DisplayNameResource("UPM_IPS.XCYLSProyectoIPS.Entidad.DisplayName", typeof(global::UPM_IPS.XCYLSProyectoIPS.XCYLSProyectoIPSDomainModel), "UPM_IPS.XCYLSProyectoIPS.GeneratedCode.DomainModelResx")]
	[DslDesign::DescriptionResource("UPM_IPS.XCYLSProyectoIPS.Entidad.Description", typeof(global::UPM_IPS.XCYLSProyectoIPS.XCYLSProyectoIPSDomainModel), "UPM_IPS.XCYLSProyectoIPS.GeneratedCode.DomainModelResx")]
	[DslModeling::DomainModelOwner(typeof(global::UPM_IPS.XCYLSProyectoIPS.XCYLSProyectoIPSDomainModel))]
	[global::System.CLSCompliant(true)]
	[global::System.Diagnostics.DebuggerDisplay("{GetType().Name,nq} (Name = {namePropertyStorage})")]
	[DslModeling::DomainObjectId("d4875884-1061-4bba-834c-4cb0a9f93791")]
	public partial class Entidad : DslModeling::ModelElement
	{
		#region Constructors, domain class Id
	
		/// <summary>
		/// Entidad domain class Id.
		/// </summary>
		public static readonly new global::System.Guid DomainClassId = new global::System.Guid(0xd4875884, 0x1061, 0x4bba, 0x83, 0x4c, 0x4c, 0xb0, 0xa9, 0xf9, 0x37, 0x91);
		/// <summary>
		/// Constructor
		/// </summary>
		/// <param name="store">Store where new element is to be created.</param>
		/// <param name="propertyAssignments">List of domain property id/value pairs to set once the element is created.</param>
		public Entidad(DslModeling::Store store, params DslModeling::PropertyAssignment[] propertyAssignments)
			: this(store != null ? store.DefaultPartitionForClass(DomainClassId) : null, propertyAssignments)
		{
		}
		
		/// <summary>
		/// Constructor
		/// </summary>
		/// <param name="partition">Partition where new element is to be created.</param>
		/// <param name="propertyAssignments">List of domain property id/value pairs to set once the element is created.</param>
		public Entidad(DslModeling::Partition partition, params DslModeling::PropertyAssignment[] propertyAssignments)
			: base(partition, propertyAssignments)
		{
		}
		#endregion
		#region Name domain property code
		
		/// <summary>
		/// Name domain property Id.
		/// </summary>
		public static readonly global::System.Guid NameDomainPropertyId = new global::System.Guid(0x9177bfe2, 0x3722, 0x467a, 0x96, 0x37, 0x36, 0x94, 0xb9, 0x85, 0x8e, 0x99);
		
		/// <summary>
		/// Storage for Name
		/// </summary>
		private global::System.String namePropertyStorage = string.Empty;
		
		/// <summary>
		/// Gets or sets the value of Name domain property.
		/// Description for UPM_IPS.XCYLSProyectoIPS.Entidad.Name
		/// </summary>
		[DslDesign::DisplayNameResource("UPM_IPS.XCYLSProyectoIPS.Entidad/Name.DisplayName", typeof(global::UPM_IPS.XCYLSProyectoIPS.XCYLSProyectoIPSDomainModel), "UPM_IPS.XCYLSProyectoIPS.GeneratedCode.DomainModelResx")]
		[DslDesign::DescriptionResource("UPM_IPS.XCYLSProyectoIPS.Entidad/Name.Description", typeof(global::UPM_IPS.XCYLSProyectoIPS.XCYLSProyectoIPSDomainModel), "UPM_IPS.XCYLSProyectoIPS.GeneratedCode.DomainModelResx")]
		[DslModeling::ElementName]
		[DslModeling::DomainObjectId("9177bfe2-3722-467a-9637-3694b9858e99")]
		public global::System.String Name
		{
			[global::System.Diagnostics.DebuggerStepThrough]
			get
			{
				return namePropertyStorage;
			}
			[global::System.Diagnostics.DebuggerStepThrough]
			set
			{
				NamePropertyHandler.Instance.SetValue(this, value);
			}
		}
		/// <summary>
		/// Value handler for the Entidad.Name domain property.
		/// </summary>
		internal sealed partial class NamePropertyHandler : DslModeling::DomainPropertyValueHandler<Entidad, global::System.String>
		{
			private NamePropertyHandler() { }
		
			/// <summary>
			/// Gets the singleton instance of the Entidad.Name domain property value handler.
			/// </summary>
			public static readonly NamePropertyHandler Instance = new NamePropertyHandler();
		
			/// <summary>
			/// Gets the Id of the Entidad.Name domain property.
			/// </summary>
			public sealed override global::System.Guid DomainPropertyId
			{
				[global::System.Diagnostics.DebuggerStepThrough]
				get
				{
					return NameDomainPropertyId;
				}
			}
			
			/// <summary>
			/// Gets a strongly-typed value of the property on specified element.
			/// </summary>
			/// <param name="element">Element which owns the property.</param>
			/// <returns>Property value.</returns>
			public override sealed global::System.String GetValue(Entidad element)
			{
				if (element == null) throw new global::System.ArgumentNullException("element");
				return element.namePropertyStorage;
			}
		
			/// <summary>
			/// Sets property value on an element.
			/// </summary>
			/// <param name="element">Element which owns the property.</param>
			/// <param name="newValue">New property value.</param>
			public override sealed void SetValue(Entidad element, global::System.String newValue)
			{
				if (element == null) throw new global::System.ArgumentNullException("element");
		
				global::System.String oldValue = GetValue(element);
				if (newValue != oldValue)
				{
					ValueChanging(element, oldValue, newValue);
					element.namePropertyStorage = newValue;
					ValueChanged(element, oldValue, newValue);
				}
			}
		}
		
		#endregion
		#region DeraWebIPS opposite domain role accessor
		/// <summary>
		/// Gets or sets DeraWebIPS.
		/// Description for UPM_IPS.XCYLSProyectoIPS.DeraWebIPSHasEntidad.Entidad
		/// </summary>
		public virtual DeraWebIPS DeraWebIPS
		{
			[global::System.Diagnostics.DebuggerStepThrough]
			get
			{
				return DslModeling::DomainRoleInfo.GetLinkedElement(this, global::UPM_IPS.XCYLSProyectoIPS.DeraWebIPSHasEntidad.EntidadDomainRoleId) as DeraWebIPS;
			}
			[global::System.Diagnostics.DebuggerStepThrough]
			set
			{
				DslModeling::DomainRoleInfo.SetLinkedElement(this, global::UPM_IPS.XCYLSProyectoIPS.DeraWebIPSHasEntidad.EntidadDomainRoleId, value);
			}
		}
		#endregion
		#region Relacioned opposite domain role accessor
		
		/// <summary>
		/// Gets a list of Relacioned.
		/// Description for UPM_IPS.XCYLSProyectoIPS.EntidadReferencesRelacioned.Entidad
		/// </summary>
		public virtual DslModeling::LinkedElementCollection<Relacion> Relacioned
		{
			[global::System.Diagnostics.DebuggerStepThrough]
			get
			{
				return GetRoleCollection<DslModeling::LinkedElementCollection<Relacion>, Relacion>(global::UPM_IPS.XCYLSProyectoIPS.EntidadReferencesRelacioned.EntidadDomainRoleId);
			}
		}
		#endregion
		#region AtributoEntidad opposite domain role accessor
		
		/// <summary>
		/// Gets a list of AtributoEntidad.
		/// Description for UPM_IPS.XCYLSProyectoIPS.EntidadHasAtributoEntidad.Entidad
		/// </summary>
		public virtual DslModeling::LinkedElementCollection<AtributoEntidad> AtributoEntidad
		{
			[global::System.Diagnostics.DebuggerStepThrough]
			get
			{
				return GetRoleCollection<DslModeling::LinkedElementCollection<AtributoEntidad>, AtributoEntidad>(global::UPM_IPS.XCYLSProyectoIPS.EntidadHasAtributoEntidad.EntidadDomainRoleId);
			}
		}
		#endregion
		#region AtributoClaves opposite domain role accessor
		
		/// <summary>
		/// Gets a list of AtributoClaves.
		/// Description for UPM_IPS.XCYLSProyectoIPS.EntidadHasAtributoClaves.Entidad
		/// </summary>
		public virtual DslModeling::LinkedElementCollection<AtributoClave> AtributoClaves
		{
			[global::System.Diagnostics.DebuggerStepThrough]
			get
			{
				return GetRoleCollection<DslModeling::LinkedElementCollection<AtributoClave>, AtributoClave>(global::UPM_IPS.XCYLSProyectoIPS.EntidadHasAtributoClaves.EntidadDomainRoleId);
			}
		}
		#endregion
		#region ElementGroupPrototype Merge methods
		/// <summary>
		/// Returns a value indicating whether the source element represented by the
		/// specified root ProtoElement can be added to this element.
		/// </summary>
		/// <param name="rootElement">
		/// The root ProtoElement representing a source element.  This can be null, 
		/// in which case the ElementGroupPrototype does not contain an ProtoElements
		/// and the code should inspect the ElementGroupPrototype context information.
		/// </param>
		/// <param name="elementGroupPrototype">The ElementGroupPrototype that contains the root ProtoElement.</param>
		/// <returns>true if the source element represented by the ProtoElement can be added to this target element.</returns>
		protected override bool CanMerge(DslModeling::ProtoElementBase rootElement, DslModeling::ElementGroupPrototype elementGroupPrototype)
		{
			if ( elementGroupPrototype == null ) throw new global::System.ArgumentNullException("elementGroupPrototype");
			
			if (rootElement != null)
			{
				DslModeling::DomainClassInfo rootElementDomainInfo = this.Partition.DomainDataDirectory.GetDomainClass(rootElement.DomainClassId);
				
				if (rootElementDomainInfo.IsDerivedFrom(global::UPM_IPS.XCYLSProyectoIPS.AtributoEntidad.DomainClassId)) 
				{
					return true;
				}
				
				if (rootElementDomainInfo.IsDerivedFrom(global::UPM_IPS.XCYLSProyectoIPS.AtributoClave.DomainClassId)) 
				{
					return true;
				}
			}
			return base.CanMerge(rootElement, elementGroupPrototype);
		}
		
		/// <summary>
		/// Called by the Merge process to create a relationship between 
		/// this target element and the specified source element. 
		/// Typically, a parent-child relationship is established
		/// between the target element (the parent) and the source element 
		/// (the child), but any relationship can be established.
		/// </summary>
		/// <param name="sourceElement">The element that is to be related to this model element.</param>
		/// <param name="elementGroup">The group of source ModelElements that have been rehydrated into the target store.</param>
		/// <remarks>
		/// This method is overriden to create the relationship between the target element and the specified source element.
		/// The base method does nothing.
		/// </remarks>
		protected override void MergeRelate(DslModeling::ModelElement sourceElement, DslModeling::ElementGroup elementGroup)
		{
			// In general, sourceElement is allowed to be null, meaning that the elementGroup must be parsed for special cases.
			// However this is not supported in generated code.  Use double-deriving on this class and then override MergeRelate completely if you 
			// need to support this case.
			if ( sourceElement == null ) throw new global::System.ArgumentNullException("sourceElement");
		
				
			global::UPM_IPS.XCYLSProyectoIPS.AtributoEntidad sourceAtributoEntidad1 = sourceElement as global::UPM_IPS.XCYLSProyectoIPS.AtributoEntidad;
			if (sourceAtributoEntidad1 != null)
			{
				// Create link for path EntidadHasAtributoEntidad.AtributoEntidad
				this.AtributoEntidad.Add(sourceAtributoEntidad1);

				return;
			}
				
			global::UPM_IPS.XCYLSProyectoIPS.AtributoClave sourceAtributoClave2 = sourceElement as global::UPM_IPS.XCYLSProyectoIPS.AtributoClave;
			if (sourceAtributoClave2 != null)
			{
				// Create link for path EntidadHasAtributoClaves.AtributoClaves
				this.AtributoClaves.Add(sourceAtributoClave2);

				return;
			}
		
			// Sdk workaround to runtime bug #879350 (DSL: can't copy and paste a MEL that has a MEX). Avoid MergeRelate on ModelElementExtension
			// during a "Paste".
			if (sourceElement is DslModeling::ExtensionElement
				&& sourceElement.Store.TransactionManager.CurrentTransaction.TopLevelTransaction.Context.ContextInfo.ContainsKey("{9DAFD42A-DC0E-4d78-8C3F-8266B2CF8B33}"))
			{
				return;
			}
		
			// Fall through to base class if this class hasn't handled the merge.
			base.MergeRelate(sourceElement, elementGroup);
		}
		
		/// <summary>
		/// Performs operation opposite to MergeRelate - i.e. disconnects a given
		/// element from the current one (removes links created by MergeRelate).
		/// </summary>
		/// <param name="sourceElement">Element to be unmerged/disconnected.</param>
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1800:DoNotCastUnnecessarily")]
		protected override void MergeDisconnect(DslModeling::ModelElement sourceElement)
		{
			if (sourceElement == null) throw new global::System.ArgumentNullException("sourceElement");
				
			global::UPM_IPS.XCYLSProyectoIPS.AtributoEntidad sourceAtributoEntidad1 = sourceElement as global::UPM_IPS.XCYLSProyectoIPS.AtributoEntidad;
			if (sourceAtributoEntidad1 != null)
			{
				// Delete link for path EntidadHasAtributoEntidad.AtributoEntidad
				
				foreach (DslModeling::ElementLink link in global::UPM_IPS.XCYLSProyectoIPS.EntidadHasAtributoEntidad.GetLinks((global::UPM_IPS.XCYLSProyectoIPS.Entidad)this, sourceAtributoEntidad1))
				{
					// Delete the link, but without possible delete propagation to the element since it's moving to a new location.
					link.Delete(global::UPM_IPS.XCYLSProyectoIPS.EntidadHasAtributoEntidad.EntidadDomainRoleId, global::UPM_IPS.XCYLSProyectoIPS.EntidadHasAtributoEntidad.AtributoEntidadDomainRoleId);
				}

				return;
			}
				
			global::UPM_IPS.XCYLSProyectoIPS.AtributoClave sourceAtributoClave2 = sourceElement as global::UPM_IPS.XCYLSProyectoIPS.AtributoClave;
			if (sourceAtributoClave2 != null)
			{
				// Delete link for path EntidadHasAtributoClaves.AtributoClaves
				
				foreach (DslModeling::ElementLink link in global::UPM_IPS.XCYLSProyectoIPS.EntidadHasAtributoClaves.GetLinks((global::UPM_IPS.XCYLSProyectoIPS.Entidad)this, sourceAtributoClave2))
				{
					// Delete the link, but without possible delete propagation to the element since it's moving to a new location.
					link.Delete(global::UPM_IPS.XCYLSProyectoIPS.EntidadHasAtributoClaves.EntidadDomainRoleId, global::UPM_IPS.XCYLSProyectoIPS.EntidadHasAtributoClaves.AtributoClaveDomainRoleId);
				}

				return;
			}
			// Fall through to base class if this class hasn't handled the unmerge.
			base.MergeDisconnect(sourceElement);
		}
		#endregion
	}
}
namespace UPM_IPS.XCYLSProyectoIPS
{
	/// <summary>
	/// DomainClass Relacion
	/// Description for UPM_IPS.XCYLSProyectoIPS.Relacion
	/// </summary>
	[DslDesign::DisplayNameResource("UPM_IPS.XCYLSProyectoIPS.Relacion.DisplayName", typeof(global::UPM_IPS.XCYLSProyectoIPS.XCYLSProyectoIPSDomainModel), "UPM_IPS.XCYLSProyectoIPS.GeneratedCode.DomainModelResx")]
	[DslDesign::DescriptionResource("UPM_IPS.XCYLSProyectoIPS.Relacion.Description", typeof(global::UPM_IPS.XCYLSProyectoIPS.XCYLSProyectoIPSDomainModel), "UPM_IPS.XCYLSProyectoIPS.GeneratedCode.DomainModelResx")]
	[DslModeling::DomainModelOwner(typeof(global::UPM_IPS.XCYLSProyectoIPS.XCYLSProyectoIPSDomainModel))]
	[global::System.CLSCompliant(true)]
	[DslModeling::DomainObjectId("e3994a65-dca4-49b1-8baa-b291b0e3ff95")]
	public partial class Relacion : DslModeling::ModelElement
	{
		#region Constructors, domain class Id
	
		/// <summary>
		/// Relacion domain class Id.
		/// </summary>
		public static readonly new global::System.Guid DomainClassId = new global::System.Guid(0xe3994a65, 0xdca4, 0x49b1, 0x8b, 0xaa, 0xb2, 0x91, 0xb0, 0xe3, 0xff, 0x95);
		/// <summary>
		/// Constructor
		/// </summary>
		/// <param name="store">Store where new element is to be created.</param>
		/// <param name="propertyAssignments">List of domain property id/value pairs to set once the element is created.</param>
		public Relacion(DslModeling::Store store, params DslModeling::PropertyAssignment[] propertyAssignments)
			: this(store != null ? store.DefaultPartitionForClass(DomainClassId) : null, propertyAssignments)
		{
		}
		
		/// <summary>
		/// Constructor
		/// </summary>
		/// <param name="partition">Partition where new element is to be created.</param>
		/// <param name="propertyAssignments">List of domain property id/value pairs to set once the element is created.</param>
		public Relacion(DslModeling::Partition partition, params DslModeling::PropertyAssignment[] propertyAssignments)
			: base(partition, propertyAssignments)
		{
		}
		#endregion
		#region Entidad opposite domain role accessor
		
		/// <summary>
		/// Gets a list of Entidad.
		/// Description for UPM_IPS.XCYLSProyectoIPS.EntidadReferencesRelacioned.Relacion
		/// </summary>
		public virtual DslModeling::LinkedElementCollection<Entidad> Entidad
		{
			[global::System.Diagnostics.DebuggerStepThrough]
			get
			{
				return GetRoleCollection<DslModeling::LinkedElementCollection<Entidad>, Entidad>(global::UPM_IPS.XCYLSProyectoIPS.EntidadReferencesRelacioned.RelacionDomainRoleId);
			}
		}
		#endregion
		#region DeraWebIPS opposite domain role accessor
		/// <summary>
		/// Gets or sets DeraWebIPS.
		/// Description for UPM_IPS.XCYLSProyectoIPS.DeraWebIPSHasRelacioned.Relacion
		/// </summary>
		public virtual DeraWebIPS DeraWebIPS
		{
			[global::System.Diagnostics.DebuggerStepThrough]
			get
			{
				return DslModeling::DomainRoleInfo.GetLinkedElement(this, global::UPM_IPS.XCYLSProyectoIPS.DeraWebIPSHasRelacioned.RelacionDomainRoleId) as DeraWebIPS;
			}
			[global::System.Diagnostics.DebuggerStepThrough]
			set
			{
				DslModeling::DomainRoleInfo.SetLinkedElement(this, global::UPM_IPS.XCYLSProyectoIPS.DeraWebIPSHasRelacioned.RelacionDomainRoleId, value);
			}
		}
		#endregion
		#region AtributoRelacioned opposite domain role accessor
		
		/// <summary>
		/// Gets a list of AtributoRelacioned.
		/// Description for UPM_IPS.XCYLSProyectoIPS.RelacionHasAtributoRelacioned.Relacion
		/// </summary>
		public virtual DslModeling::LinkedElementCollection<AtributoRelacion> AtributoRelacioned
		{
			[global::System.Diagnostics.DebuggerStepThrough]
			get
			{
				return GetRoleCollection<DslModeling::LinkedElementCollection<AtributoRelacion>, AtributoRelacion>(global::UPM_IPS.XCYLSProyectoIPS.RelacionHasAtributoRelacioned.RelacionDomainRoleId);
			}
		}
		#endregion
		#region ElementGroupPrototype Merge methods
		/// <summary>
		/// Returns a value indicating whether the source element represented by the
		/// specified root ProtoElement can be added to this element.
		/// </summary>
		/// <param name="rootElement">
		/// The root ProtoElement representing a source element.  This can be null, 
		/// in which case the ElementGroupPrototype does not contain an ProtoElements
		/// and the code should inspect the ElementGroupPrototype context information.
		/// </param>
		/// <param name="elementGroupPrototype">The ElementGroupPrototype that contains the root ProtoElement.</param>
		/// <returns>true if the source element represented by the ProtoElement can be added to this target element.</returns>
		protected override bool CanMerge(DslModeling::ProtoElementBase rootElement, DslModeling::ElementGroupPrototype elementGroupPrototype)
		{
			if ( elementGroupPrototype == null ) throw new global::System.ArgumentNullException("elementGroupPrototype");
			
			if (rootElement != null)
			{
				DslModeling::DomainClassInfo rootElementDomainInfo = this.Partition.DomainDataDirectory.GetDomainClass(rootElement.DomainClassId);
				
				if (rootElementDomainInfo.IsDerivedFrom(global::UPM_IPS.XCYLSProyectoIPS.AtributoRelacion.DomainClassId)) 
				{
					return true;
				}
			}
			return base.CanMerge(rootElement, elementGroupPrototype);
		}
		
		/// <summary>
		/// Called by the Merge process to create a relationship between 
		/// this target element and the specified source element. 
		/// Typically, a parent-child relationship is established
		/// between the target element (the parent) and the source element 
		/// (the child), but any relationship can be established.
		/// </summary>
		/// <param name="sourceElement">The element that is to be related to this model element.</param>
		/// <param name="elementGroup">The group of source ModelElements that have been rehydrated into the target store.</param>
		/// <remarks>
		/// This method is overriden to create the relationship between the target element and the specified source element.
		/// The base method does nothing.
		/// </remarks>
		protected override void MergeRelate(DslModeling::ModelElement sourceElement, DslModeling::ElementGroup elementGroup)
		{
			// In general, sourceElement is allowed to be null, meaning that the elementGroup must be parsed for special cases.
			// However this is not supported in generated code.  Use double-deriving on this class and then override MergeRelate completely if you 
			// need to support this case.
			if ( sourceElement == null ) throw new global::System.ArgumentNullException("sourceElement");
		
				
			global::UPM_IPS.XCYLSProyectoIPS.AtributoRelacion sourceAtributoRelacion1 = sourceElement as global::UPM_IPS.XCYLSProyectoIPS.AtributoRelacion;
			if (sourceAtributoRelacion1 != null)
			{
				// Create link for path RelacionHasAtributoRelacioned.AtributoRelacioned
				this.AtributoRelacioned.Add(sourceAtributoRelacion1);

				return;
			}
		
			// Sdk workaround to runtime bug #879350 (DSL: can't copy and paste a MEL that has a MEX). Avoid MergeRelate on ModelElementExtension
			// during a "Paste".
			if (sourceElement is DslModeling::ExtensionElement
				&& sourceElement.Store.TransactionManager.CurrentTransaction.TopLevelTransaction.Context.ContextInfo.ContainsKey("{9DAFD42A-DC0E-4d78-8C3F-8266B2CF8B33}"))
			{
				return;
			}
		
			// Fall through to base class if this class hasn't handled the merge.
			base.MergeRelate(sourceElement, elementGroup);
		}
		
		/// <summary>
		/// Performs operation opposite to MergeRelate - i.e. disconnects a given
		/// element from the current one (removes links created by MergeRelate).
		/// </summary>
		/// <param name="sourceElement">Element to be unmerged/disconnected.</param>
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1800:DoNotCastUnnecessarily")]
		protected override void MergeDisconnect(DslModeling::ModelElement sourceElement)
		{
			if (sourceElement == null) throw new global::System.ArgumentNullException("sourceElement");
				
			global::UPM_IPS.XCYLSProyectoIPS.AtributoRelacion sourceAtributoRelacion1 = sourceElement as global::UPM_IPS.XCYLSProyectoIPS.AtributoRelacion;
			if (sourceAtributoRelacion1 != null)
			{
				// Delete link for path RelacionHasAtributoRelacioned.AtributoRelacioned
				
				foreach (DslModeling::ElementLink link in global::UPM_IPS.XCYLSProyectoIPS.RelacionHasAtributoRelacioned.GetLinks((global::UPM_IPS.XCYLSProyectoIPS.Relacion)this, sourceAtributoRelacion1))
				{
					// Delete the link, but without possible delete propagation to the element since it's moving to a new location.
					link.Delete(global::UPM_IPS.XCYLSProyectoIPS.RelacionHasAtributoRelacioned.RelacionDomainRoleId, global::UPM_IPS.XCYLSProyectoIPS.RelacionHasAtributoRelacioned.AtributoRelacionDomainRoleId);
				}

				return;
			}
			// Fall through to base class if this class hasn't handled the unmerge.
			base.MergeDisconnect(sourceElement);
		}
		#endregion
	}
}
namespace UPM_IPS.XCYLSProyectoIPS
{
	/// <summary>
	/// DomainClass AtributoEntidad
	/// Description for UPM_IPS.XCYLSProyectoIPS.AtributoEntidad
	/// </summary>
	[DslDesign::DisplayNameResource("UPM_IPS.XCYLSProyectoIPS.AtributoEntidad.DisplayName", typeof(global::UPM_IPS.XCYLSProyectoIPS.XCYLSProyectoIPSDomainModel), "UPM_IPS.XCYLSProyectoIPS.GeneratedCode.DomainModelResx")]
	[DslDesign::DescriptionResource("UPM_IPS.XCYLSProyectoIPS.AtributoEntidad.Description", typeof(global::UPM_IPS.XCYLSProyectoIPS.XCYLSProyectoIPSDomainModel), "UPM_IPS.XCYLSProyectoIPS.GeneratedCode.DomainModelResx")]
	[DslModeling::DomainModelOwner(typeof(global::UPM_IPS.XCYLSProyectoIPS.XCYLSProyectoIPSDomainModel))]
	[global::System.CLSCompliant(true)]
	[DslModeling::DomainObjectId("b59878ed-1691-4098-8655-d3a0ad522f67")]
	public partial class AtributoEntidad : DslModeling::ModelElement
	{
		#region Constructors, domain class Id
	
		/// <summary>
		/// AtributoEntidad domain class Id.
		/// </summary>
		public static readonly new global::System.Guid DomainClassId = new global::System.Guid(0xb59878ed, 0x1691, 0x4098, 0x86, 0x55, 0xd3, 0xa0, 0xad, 0x52, 0x2f, 0x67);
		/// <summary>
		/// Constructor
		/// </summary>
		/// <param name="store">Store where new element is to be created.</param>
		/// <param name="propertyAssignments">List of domain property id/value pairs to set once the element is created.</param>
		public AtributoEntidad(DslModeling::Store store, params DslModeling::PropertyAssignment[] propertyAssignments)
			: this(store != null ? store.DefaultPartitionForClass(DomainClassId) : null, propertyAssignments)
		{
		}
		
		/// <summary>
		/// Constructor
		/// </summary>
		/// <param name="partition">Partition where new element is to be created.</param>
		/// <param name="propertyAssignments">List of domain property id/value pairs to set once the element is created.</param>
		public AtributoEntidad(DslModeling::Partition partition, params DslModeling::PropertyAssignment[] propertyAssignments)
			: base(partition, propertyAssignments)
		{
		}
		#endregion
		#region Entidad opposite domain role accessor
		/// <summary>
		/// Gets or sets Entidad.
		/// Description for
		/// UPM_IPS.XCYLSProyectoIPS.EntidadHasAtributoEntidad.AtributoEntidad
		/// </summary>
		public virtual Entidad Entidad
		{
			[global::System.Diagnostics.DebuggerStepThrough]
			get
			{
				return DslModeling::DomainRoleInfo.GetLinkedElement(this, global::UPM_IPS.XCYLSProyectoIPS.EntidadHasAtributoEntidad.AtributoEntidadDomainRoleId) as Entidad;
			}
			[global::System.Diagnostics.DebuggerStepThrough]
			set
			{
				DslModeling::DomainRoleInfo.SetLinkedElement(this, global::UPM_IPS.XCYLSProyectoIPS.EntidadHasAtributoEntidad.AtributoEntidadDomainRoleId, value);
			}
		}
		#endregion
	}
}
namespace UPM_IPS.XCYLSProyectoIPS
{
	/// <summary>
	/// DomainClass AtributoRelacion
	/// Description for UPM_IPS.XCYLSProyectoIPS.AtributoRelacion
	/// </summary>
	[DslDesign::DisplayNameResource("UPM_IPS.XCYLSProyectoIPS.AtributoRelacion.DisplayName", typeof(global::UPM_IPS.XCYLSProyectoIPS.XCYLSProyectoIPSDomainModel), "UPM_IPS.XCYLSProyectoIPS.GeneratedCode.DomainModelResx")]
	[DslDesign::DescriptionResource("UPM_IPS.XCYLSProyectoIPS.AtributoRelacion.Description", typeof(global::UPM_IPS.XCYLSProyectoIPS.XCYLSProyectoIPSDomainModel), "UPM_IPS.XCYLSProyectoIPS.GeneratedCode.DomainModelResx")]
	[DslModeling::DomainModelOwner(typeof(global::UPM_IPS.XCYLSProyectoIPS.XCYLSProyectoIPSDomainModel))]
	[global::System.CLSCompliant(true)]
	[DslModeling::DomainObjectId("863fd30e-be10-41dc-9c2c-75e56b3e7a98")]
	public partial class AtributoRelacion : DslModeling::ModelElement
	{
		#region Constructors, domain class Id
	
		/// <summary>
		/// AtributoRelacion domain class Id.
		/// </summary>
		public static readonly new global::System.Guid DomainClassId = new global::System.Guid(0x863fd30e, 0xbe10, 0x41dc, 0x9c, 0x2c, 0x75, 0xe5, 0x6b, 0x3e, 0x7a, 0x98);
		/// <summary>
		/// Constructor
		/// </summary>
		/// <param name="store">Store where new element is to be created.</param>
		/// <param name="propertyAssignments">List of domain property id/value pairs to set once the element is created.</param>
		public AtributoRelacion(DslModeling::Store store, params DslModeling::PropertyAssignment[] propertyAssignments)
			: this(store != null ? store.DefaultPartitionForClass(DomainClassId) : null, propertyAssignments)
		{
		}
		
		/// <summary>
		/// Constructor
		/// </summary>
		/// <param name="partition">Partition where new element is to be created.</param>
		/// <param name="propertyAssignments">List of domain property id/value pairs to set once the element is created.</param>
		public AtributoRelacion(DslModeling::Partition partition, params DslModeling::PropertyAssignment[] propertyAssignments)
			: base(partition, propertyAssignments)
		{
		}
		#endregion
		#region Relacion opposite domain role accessor
		/// <summary>
		/// Gets or sets Relacion.
		/// Description for
		/// UPM_IPS.XCYLSProyectoIPS.RelacionHasAtributoRelacioned.AtributoRelacion
		/// </summary>
		public virtual Relacion Relacion
		{
			[global::System.Diagnostics.DebuggerStepThrough]
			get
			{
				return DslModeling::DomainRoleInfo.GetLinkedElement(this, global::UPM_IPS.XCYLSProyectoIPS.RelacionHasAtributoRelacioned.AtributoRelacionDomainRoleId) as Relacion;
			}
			[global::System.Diagnostics.DebuggerStepThrough]
			set
			{
				DslModeling::DomainRoleInfo.SetLinkedElement(this, global::UPM_IPS.XCYLSProyectoIPS.RelacionHasAtributoRelacioned.AtributoRelacionDomainRoleId, value);
			}
		}
		#endregion
	}
}
namespace UPM_IPS.XCYLSProyectoIPS
{
	/// <summary>
	/// DomainClass AtributoClave
	/// Description for UPM_IPS.XCYLSProyectoIPS.AtributoClave
	/// </summary>
	[DslDesign::DisplayNameResource("UPM_IPS.XCYLSProyectoIPS.AtributoClave.DisplayName", typeof(global::UPM_IPS.XCYLSProyectoIPS.XCYLSProyectoIPSDomainModel), "UPM_IPS.XCYLSProyectoIPS.GeneratedCode.DomainModelResx")]
	[DslDesign::DescriptionResource("UPM_IPS.XCYLSProyectoIPS.AtributoClave.Description", typeof(global::UPM_IPS.XCYLSProyectoIPS.XCYLSProyectoIPSDomainModel), "UPM_IPS.XCYLSProyectoIPS.GeneratedCode.DomainModelResx")]
	[DslModeling::DomainModelOwner(typeof(global::UPM_IPS.XCYLSProyectoIPS.XCYLSProyectoIPSDomainModel))]
	[global::System.CLSCompliant(true)]
	[DslModeling::DomainObjectId("2995b03f-8599-42fe-833c-be8899997af1")]
	public partial class AtributoClave : DslModeling::ModelElement
	{
		#region Constructors, domain class Id
	
		/// <summary>
		/// AtributoClave domain class Id.
		/// </summary>
		public static readonly new global::System.Guid DomainClassId = new global::System.Guid(0x2995b03f, 0x8599, 0x42fe, 0x83, 0x3c, 0xbe, 0x88, 0x99, 0x99, 0x7a, 0xf1);
		/// <summary>
		/// Constructor
		/// </summary>
		/// <param name="store">Store where new element is to be created.</param>
		/// <param name="propertyAssignments">List of domain property id/value pairs to set once the element is created.</param>
		public AtributoClave(DslModeling::Store store, params DslModeling::PropertyAssignment[] propertyAssignments)
			: this(store != null ? store.DefaultPartitionForClass(DomainClassId) : null, propertyAssignments)
		{
		}
		
		/// <summary>
		/// Constructor
		/// </summary>
		/// <param name="partition">Partition where new element is to be created.</param>
		/// <param name="propertyAssignments">List of domain property id/value pairs to set once the element is created.</param>
		public AtributoClave(DslModeling::Partition partition, params DslModeling::PropertyAssignment[] propertyAssignments)
			: base(partition, propertyAssignments)
		{
		}
		#endregion
		#region Entidad opposite domain role accessor
		/// <summary>
		/// Gets or sets Entidad.
		/// Description for UPM_IPS.XCYLSProyectoIPS.EntidadHasAtributoClaves.AtributoClave
		/// </summary>
		public virtual Entidad Entidad
		{
			[global::System.Diagnostics.DebuggerStepThrough]
			get
			{
				return DslModeling::DomainRoleInfo.GetLinkedElement(this, global::UPM_IPS.XCYLSProyectoIPS.EntidadHasAtributoClaves.AtributoClaveDomainRoleId) as Entidad;
			}
			[global::System.Diagnostics.DebuggerStepThrough]
			set
			{
				DslModeling::DomainRoleInfo.SetLinkedElement(this, global::UPM_IPS.XCYLSProyectoIPS.EntidadHasAtributoClaves.AtributoClaveDomainRoleId, value);
			}
		}
		#endregion
	}
}
