//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using DslModeling = global::Microsoft.VisualStudio.Modeling;
using DslDesign = global::Microsoft.VisualStudio.Modeling.Design;
namespace UPM_IPS.XCYLSProyectoIPS
{
	/// <summary>
	/// DomainRelationship DeraWebIPSHasEntidad
	/// Description for UPM_IPS.XCYLSProyectoIPS.DeraWebIPSHasEntidad
	/// </summary>
	[DslDesign::DisplayNameResource("UPM_IPS.XCYLSProyectoIPS.DeraWebIPSHasEntidad.DisplayName", typeof(global::UPM_IPS.XCYLSProyectoIPS.XCYLSProyectoIPSDomainModel), "UPM_IPS.XCYLSProyectoIPS.GeneratedCode.DomainModelResx")]
	[DslDesign::DescriptionResource("UPM_IPS.XCYLSProyectoIPS.DeraWebIPSHasEntidad.Description", typeof(global::UPM_IPS.XCYLSProyectoIPS.XCYLSProyectoIPSDomainModel), "UPM_IPS.XCYLSProyectoIPS.GeneratedCode.DomainModelResx")]
	[DslModeling::DomainModelOwner(typeof(global::UPM_IPS.XCYLSProyectoIPS.XCYLSProyectoIPSDomainModel))]
	[global::System.CLSCompliant(true)]
	[DslModeling::DomainRelationship(IsEmbedding=true)]
	[DslModeling::DomainObjectId("43e760c1-6238-4b7c-9c06-1fdff0e2c9fc")]
	public partial class DeraWebIPSHasEntidad : DslModeling::ElementLink
	{
		#region Constructors, domain class Id
		
		/// <summary>
		/// DeraWebIPSHasEntidad domain class Id.
		/// </summary>
		public static readonly new global::System.Guid DomainClassId = new global::System.Guid(0x43e760c1, 0x6238, 0x4b7c, 0x9c, 0x06, 0x1f, 0xdf, 0xf0, 0xe2, 0xc9, 0xfc);
	
				
		/// <summary>
		/// Constructor
		/// Creates a DeraWebIPSHasEntidad link in the same Partition as the given DeraWebIPS
		/// </summary>
		/// <param name="source">DeraWebIPS to use as the source of the relationship.</param>
		/// <param name="target">Entidad to use as the target of the relationship.</param>
		public DeraWebIPSHasEntidad(DeraWebIPS source, Entidad target)
			: base((source != null ? source.Partition : null), new DslModeling::RoleAssignment[]{new DslModeling::RoleAssignment(DeraWebIPSHasEntidad.DeraWebIPSDomainRoleId, source), new DslModeling::RoleAssignment(DeraWebIPSHasEntidad.EntidadDomainRoleId, target)}, null)
		{
		}
		
		/// <summary>
		/// Constructor
		/// </summary>
		/// <param name="store">Store where new link is to be created.</param>
		/// <param name="roleAssignments">List of relationship role assignments.</param>
		public DeraWebIPSHasEntidad(DslModeling::Store store, params DslModeling::RoleAssignment[] roleAssignments)
			: base(store != null ? store.DefaultPartitionForClass(DomainClassId) : null, roleAssignments, null)
		{
		}
		
		/// <summary>
		/// Constructor
		/// </summary>
		/// <param name="store">Store where new link is to be created.</param>
		/// <param name="roleAssignments">List of relationship role assignments.</param>
		/// <param name="propertyAssignments">List of properties assignments to set on the new link.</param>
		public DeraWebIPSHasEntidad(DslModeling::Store store, DslModeling::RoleAssignment[] roleAssignments, DslModeling::PropertyAssignment[] propertyAssignments)
			: base(store != null ? store.DefaultPartitionForClass(DomainClassId) : null, roleAssignments, propertyAssignments)
		{
		}
		
		/// <summary>
		/// Constructor
		/// </summary>
		/// <param name="partition">Partition where new link is to be created.</param>
		/// <param name="roleAssignments">List of relationship role assignments.</param>
		public DeraWebIPSHasEntidad(DslModeling::Partition partition, params DslModeling::RoleAssignment[] roleAssignments)
			: base(partition, roleAssignments, null)
		{
		}
		
		/// <summary>
		/// Constructor
		/// </summary>
		/// <param name="partition">Partition where new link is to be created.</param>
		/// <param name="roleAssignments">List of relationship role assignments.</param>
		/// <param name="propertyAssignments">List of properties assignments to set on the new link.</param>
		public DeraWebIPSHasEntidad(DslModeling::Partition partition, DslModeling::RoleAssignment[] roleAssignments, DslModeling::PropertyAssignment[] propertyAssignments)
			: base(partition, roleAssignments, propertyAssignments)
		{
		}
		#endregion
		#region DeraWebIPS domain role code
		
		/// <summary>
		/// DeraWebIPS domain role Id.
		/// </summary>
		public static readonly global::System.Guid DeraWebIPSDomainRoleId = new global::System.Guid(0xc066d388, 0x3560, 0x4a3e, 0xb4, 0x6e, 0x31, 0x8e, 0xf2, 0x82, 0xa1, 0x7d);
		
		/// <summary>
		/// DomainRole DeraWebIPS
		/// Description for UPM_IPS.XCYLSProyectoIPS.DeraWebIPSHasEntidad.DeraWebIPS
		/// </summary>
		[DslDesign::DisplayNameResource("UPM_IPS.XCYLSProyectoIPS.DeraWebIPSHasEntidad/DeraWebIPS.DisplayName", typeof(global::UPM_IPS.XCYLSProyectoIPS.XCYLSProyectoIPSDomainModel), "UPM_IPS.XCYLSProyectoIPS.GeneratedCode.DomainModelResx")]
		[DslDesign::DescriptionResource("UPM_IPS.XCYLSProyectoIPS.DeraWebIPSHasEntidad/DeraWebIPS.Description", typeof(global::UPM_IPS.XCYLSProyectoIPS.XCYLSProyectoIPSDomainModel), "UPM_IPS.XCYLSProyectoIPS.GeneratedCode.DomainModelResx")]
		[DslModeling::DomainRole(DslModeling::DomainRoleOrder.Source, PropertyName = "Entidad", PropertyDisplayNameKey="UPM_IPS.XCYLSProyectoIPS.DeraWebIPSHasEntidad/DeraWebIPS.PropertyDisplayName",  PropagatesCopy = DslModeling::PropagatesCopyOption.PropagatesCopyToLinkAndOppositeRolePlayer, Multiplicity = DslModeling::Multiplicity.OneMany)]
		[DslModeling::DomainObjectId("c066d388-3560-4a3e-b46e-318ef282a17d")]
		public virtual DeraWebIPS DeraWebIPS
		{
			[global::System.Diagnostics.DebuggerStepThrough]
			get
			{
				return (DeraWebIPS)DslModeling::DomainRoleInfo.GetRolePlayer(this, DeraWebIPSDomainRoleId);
			}
			[global::System.Diagnostics.DebuggerStepThrough]
			set
			{
				DslModeling::DomainRoleInfo.SetRolePlayer(this, DeraWebIPSDomainRoleId, value);
			}
		}
				
		#endregion
		#region Static methods to access DeraWebIPS of a Entidad
		/// <summary>
		/// Gets DeraWebIPS.
		/// </summary>
		[global::System.Diagnostics.DebuggerStepThrough]
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1011")]
		public static DeraWebIPS GetDeraWebIPS(Entidad element)
		{
			return DslModeling::DomainRoleInfo.GetLinkedElement(element, EntidadDomainRoleId) as DeraWebIPS;
		}
		
		/// <summary>
		/// Sets DeraWebIPS.
		/// </summary>
		[global::System.Diagnostics.DebuggerStepThrough]
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1011")]
		public static void SetDeraWebIPS(Entidad element, DeraWebIPS newDeraWebIPS)
		{
			DslModeling::DomainRoleInfo.SetLinkedElement(element, EntidadDomainRoleId, newDeraWebIPS);
		}
		#endregion
		#region Entidad domain role code
		
		/// <summary>
		/// Entidad domain role Id.
		/// </summary>
		public static readonly global::System.Guid EntidadDomainRoleId = new global::System.Guid(0x0713eaea, 0xa73a, 0x436e, 0xb4, 0xff, 0x1e, 0x63, 0xf6, 0x75, 0xcd, 0xf7);
		
		/// <summary>
		/// DomainRole Entidad
		/// Description for UPM_IPS.XCYLSProyectoIPS.DeraWebIPSHasEntidad.Entidad
		/// </summary>
		[DslDesign::DisplayNameResource("UPM_IPS.XCYLSProyectoIPS.DeraWebIPSHasEntidad/Entidad.DisplayName", typeof(global::UPM_IPS.XCYLSProyectoIPS.XCYLSProyectoIPSDomainModel), "UPM_IPS.XCYLSProyectoIPS.GeneratedCode.DomainModelResx")]
		[DslDesign::DescriptionResource("UPM_IPS.XCYLSProyectoIPS.DeraWebIPSHasEntidad/Entidad.Description", typeof(global::UPM_IPS.XCYLSProyectoIPS.XCYLSProyectoIPSDomainModel), "UPM_IPS.XCYLSProyectoIPS.GeneratedCode.DomainModelResx")]
		[DslModeling::DomainRole(DslModeling::DomainRoleOrder.Target, PropertyName = "DeraWebIPS", PropertyDisplayNameKey="UPM_IPS.XCYLSProyectoIPS.DeraWebIPSHasEntidad/Entidad.PropertyDisplayName", PropagatesDelete = true,  PropagatesCopy = DslModeling::PropagatesCopyOption.DoNotPropagateCopy, Multiplicity = DslModeling::Multiplicity.One)]
		[DslModeling::DomainObjectId("0713eaea-a73a-436e-b4ff-1e63f675cdf7")]
		public virtual Entidad Entidad
		{
			[global::System.Diagnostics.DebuggerStepThrough]
			get
			{
				return (Entidad)DslModeling::DomainRoleInfo.GetRolePlayer(this, EntidadDomainRoleId);
			}
			[global::System.Diagnostics.DebuggerStepThrough]
			set
			{
				DslModeling::DomainRoleInfo.SetRolePlayer(this, EntidadDomainRoleId, value);
			}
		}
				
		#endregion
		#region Static methods to access Entidad of a DeraWebIPS
		/// <summary>
		/// Gets a list of Entidad.
		/// </summary>
		[global::System.Diagnostics.DebuggerStepThrough]
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1011")]
		public static DslModeling::LinkedElementCollection<Entidad> GetEntidad(DeraWebIPS element)
		{
			return GetRoleCollection<DslModeling::LinkedElementCollection<Entidad>, Entidad>(element, DeraWebIPSDomainRoleId);
		}
		#endregion
		#region DeraWebIPS link accessor
		/// <summary>
		/// Get the list of DeraWebIPSHasEntidad links to a DeraWebIPS.
		/// </summary>
		[global::System.Diagnostics.DebuggerStepThrough]
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1011")]
		public static global::System.Collections.ObjectModel.ReadOnlyCollection<global::UPM_IPS.XCYLSProyectoIPS.DeraWebIPSHasEntidad> GetLinksToEntidad ( global::UPM_IPS.XCYLSProyectoIPS.DeraWebIPS deraWebIPSInstance )
		{
			return DslModeling::DomainRoleInfo.GetElementLinks<global::UPM_IPS.XCYLSProyectoIPS.DeraWebIPSHasEntidad>(deraWebIPSInstance, global::UPM_IPS.XCYLSProyectoIPS.DeraWebIPSHasEntidad.DeraWebIPSDomainRoleId);
		}
		#endregion
		#region Entidad link accessor
		/// <summary>
		/// Get the DeraWebIPSHasEntidad link to a Entidad.
		/// </summary>
		[global::System.Diagnostics.DebuggerStepThrough]
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1011")]
		public static global::UPM_IPS.XCYLSProyectoIPS.DeraWebIPSHasEntidad GetLinkToDeraWebIPS (global::UPM_IPS.XCYLSProyectoIPS.Entidad entidadInstance)
		{
			global::System.Collections.Generic.IList<global::UPM_IPS.XCYLSProyectoIPS.DeraWebIPSHasEntidad> links = DslModeling::DomainRoleInfo.GetElementLinks<global::UPM_IPS.XCYLSProyectoIPS.DeraWebIPSHasEntidad>(entidadInstance, global::UPM_IPS.XCYLSProyectoIPS.DeraWebIPSHasEntidad.EntidadDomainRoleId);
			global::System.Diagnostics.Debug.Assert(links.Count <= 1, "Multiplicity of Entidad not obeyed.");
			if ( links.Count == 0 )
			{
				return null;
			}
			else
			{
				return links[0];
			}
		}
		#endregion
		#region DeraWebIPSHasEntidad instance accessors
		
		/// <summary>
		/// Get any DeraWebIPSHasEntidad links between a given DeraWebIPS and a Entidad.
		/// </summary>
		[global::System.Diagnostics.DebuggerStepThrough]
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1011")]
		public static global::System.Collections.ObjectModel.ReadOnlyCollection<global::UPM_IPS.XCYLSProyectoIPS.DeraWebIPSHasEntidad> GetLinks( global::UPM_IPS.XCYLSProyectoIPS.DeraWebIPS source, global::UPM_IPS.XCYLSProyectoIPS.Entidad target )
		{
			global::System.Collections.Generic.List<global::UPM_IPS.XCYLSProyectoIPS.DeraWebIPSHasEntidad> outLinks = new global::System.Collections.Generic.List<global::UPM_IPS.XCYLSProyectoIPS.DeraWebIPSHasEntidad>();
			global::System.Collections.Generic.IList<global::UPM_IPS.XCYLSProyectoIPS.DeraWebIPSHasEntidad> links = DslModeling::DomainRoleInfo.GetElementLinks<global::UPM_IPS.XCYLSProyectoIPS.DeraWebIPSHasEntidad>(source, global::UPM_IPS.XCYLSProyectoIPS.DeraWebIPSHasEntidad.DeraWebIPSDomainRoleId);
			foreach ( global::UPM_IPS.XCYLSProyectoIPS.DeraWebIPSHasEntidad link in links )
			{
				if ( target.Equals(link.Entidad) )
				{
					outLinks.Add(link);
				}
			}
			return outLinks.AsReadOnly();
		}
		/// <summary>
		/// Get the one DeraWebIPSHasEntidad link between a given DeraWebIPSand a Entidad.
		/// </summary>
		[global::System.Diagnostics.DebuggerStepThrough]
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1011")]
		public static global::UPM_IPS.XCYLSProyectoIPS.DeraWebIPSHasEntidad GetLink( global::UPM_IPS.XCYLSProyectoIPS.DeraWebIPS source, global::UPM_IPS.XCYLSProyectoIPS.Entidad target )
		{
			global::System.Collections.Generic.IList<global::UPM_IPS.XCYLSProyectoIPS.DeraWebIPSHasEntidad> links = DslModeling::DomainRoleInfo.GetElementLinks<global::UPM_IPS.XCYLSProyectoIPS.DeraWebIPSHasEntidad>(source, global::UPM_IPS.XCYLSProyectoIPS.DeraWebIPSHasEntidad.DeraWebIPSDomainRoleId);
			foreach ( global::UPM_IPS.XCYLSProyectoIPS.DeraWebIPSHasEntidad link in links )
			{
				if ( target.Equals(link.Entidad) )
				{
					return link;
				}
			}
			return null;
		}
		
		#endregion
	}
}
namespace UPM_IPS.XCYLSProyectoIPS
{
	/// <summary>
	/// DomainRelationship EntidadReferencesRelacioned
	/// Description for UPM_IPS.XCYLSProyectoIPS.EntidadReferencesRelacioned
	/// </summary>
	[DslDesign::DisplayNameResource("UPM_IPS.XCYLSProyectoIPS.EntidadReferencesRelacioned.DisplayName", typeof(global::UPM_IPS.XCYLSProyectoIPS.XCYLSProyectoIPSDomainModel), "UPM_IPS.XCYLSProyectoIPS.GeneratedCode.DomainModelResx")]
	[DslDesign::DescriptionResource("UPM_IPS.XCYLSProyectoIPS.EntidadReferencesRelacioned.Description", typeof(global::UPM_IPS.XCYLSProyectoIPS.XCYLSProyectoIPSDomainModel), "UPM_IPS.XCYLSProyectoIPS.GeneratedCode.DomainModelResx")]
	[DslModeling::DomainModelOwner(typeof(global::UPM_IPS.XCYLSProyectoIPS.XCYLSProyectoIPSDomainModel))]
	[global::System.CLSCompliant(true)]
	[DslModeling::DomainRelationship()]
	[DslModeling::DomainObjectId("c9ca9e99-147b-49cf-9211-b775b30e7e2b")]
	public partial class EntidadReferencesRelacioned : DslModeling::ElementLink
	{
		#region Constructors, domain class Id
		
		/// <summary>
		/// EntidadReferencesRelacioned domain class Id.
		/// </summary>
		public static readonly new global::System.Guid DomainClassId = new global::System.Guid(0xc9ca9e99, 0x147b, 0x49cf, 0x92, 0x11, 0xb7, 0x75, 0xb3, 0x0e, 0x7e, 0x2b);
	
				
		/// <summary>
		/// Constructor
		/// Creates a EntidadReferencesRelacioned link in the same Partition as the given Entidad
		/// </summary>
		/// <param name="source">Entidad to use as the source of the relationship.</param>
		/// <param name="target">Relacion to use as the target of the relationship.</param>
		public EntidadReferencesRelacioned(Entidad source, Relacion target)
			: base((source != null ? source.Partition : null), new DslModeling::RoleAssignment[]{new DslModeling::RoleAssignment(EntidadReferencesRelacioned.EntidadDomainRoleId, source), new DslModeling::RoleAssignment(EntidadReferencesRelacioned.RelacionDomainRoleId, target)}, null)
		{
		}
		
		/// <summary>
		/// Constructor
		/// </summary>
		/// <param name="store">Store where new link is to be created.</param>
		/// <param name="roleAssignments">List of relationship role assignments.</param>
		public EntidadReferencesRelacioned(DslModeling::Store store, params DslModeling::RoleAssignment[] roleAssignments)
			: base(store != null ? store.DefaultPartitionForClass(DomainClassId) : null, roleAssignments, null)
		{
		}
		
		/// <summary>
		/// Constructor
		/// </summary>
		/// <param name="store">Store where new link is to be created.</param>
		/// <param name="roleAssignments">List of relationship role assignments.</param>
		/// <param name="propertyAssignments">List of properties assignments to set on the new link.</param>
		public EntidadReferencesRelacioned(DslModeling::Store store, DslModeling::RoleAssignment[] roleAssignments, DslModeling::PropertyAssignment[] propertyAssignments)
			: base(store != null ? store.DefaultPartitionForClass(DomainClassId) : null, roleAssignments, propertyAssignments)
		{
		}
		
		/// <summary>
		/// Constructor
		/// </summary>
		/// <param name="partition">Partition where new link is to be created.</param>
		/// <param name="roleAssignments">List of relationship role assignments.</param>
		public EntidadReferencesRelacioned(DslModeling::Partition partition, params DslModeling::RoleAssignment[] roleAssignments)
			: base(partition, roleAssignments, null)
		{
		}
		
		/// <summary>
		/// Constructor
		/// </summary>
		/// <param name="partition">Partition where new link is to be created.</param>
		/// <param name="roleAssignments">List of relationship role assignments.</param>
		/// <param name="propertyAssignments">List of properties assignments to set on the new link.</param>
		public EntidadReferencesRelacioned(DslModeling::Partition partition, DslModeling::RoleAssignment[] roleAssignments, DslModeling::PropertyAssignment[] propertyAssignments)
			: base(partition, roleAssignments, propertyAssignments)
		{
		}
		#endregion
		#region Entidad domain role code
		
		/// <summary>
		/// Entidad domain role Id.
		/// </summary>
		public static readonly global::System.Guid EntidadDomainRoleId = new global::System.Guid(0xb1d93943, 0xc130, 0x46be, 0xbc, 0xda, 0x97, 0xd2, 0xf0, 0x25, 0x71, 0xe6);
		
		/// <summary>
		/// DomainRole Entidad
		/// Description for UPM_IPS.XCYLSProyectoIPS.EntidadReferencesRelacioned.Entidad
		/// </summary>
		[DslDesign::DisplayNameResource("UPM_IPS.XCYLSProyectoIPS.EntidadReferencesRelacioned/Entidad.DisplayName", typeof(global::UPM_IPS.XCYLSProyectoIPS.XCYLSProyectoIPSDomainModel), "UPM_IPS.XCYLSProyectoIPS.GeneratedCode.DomainModelResx")]
		[DslDesign::DescriptionResource("UPM_IPS.XCYLSProyectoIPS.EntidadReferencesRelacioned/Entidad.Description", typeof(global::UPM_IPS.XCYLSProyectoIPS.XCYLSProyectoIPSDomainModel), "UPM_IPS.XCYLSProyectoIPS.GeneratedCode.DomainModelResx")]
		[DslModeling::DomainRole(DslModeling::DomainRoleOrder.Source, PropertyName = "Relacioned", PropertyDisplayNameKey="UPM_IPS.XCYLSProyectoIPS.EntidadReferencesRelacioned/Entidad.PropertyDisplayName",  PropagatesCopy = DslModeling::PropagatesCopyOption.DoNotPropagateCopy, Multiplicity = DslModeling::Multiplicity.ZeroMany)]
		[DslModeling::DomainObjectId("b1d93943-c130-46be-bcda-97d2f02571e6")]
		public virtual Entidad Entidad
		{
			[global::System.Diagnostics.DebuggerStepThrough]
			get
			{
				return (Entidad)DslModeling::DomainRoleInfo.GetRolePlayer(this, EntidadDomainRoleId);
			}
			[global::System.Diagnostics.DebuggerStepThrough]
			set
			{
				DslModeling::DomainRoleInfo.SetRolePlayer(this, EntidadDomainRoleId, value);
			}
		}
				
		#endregion
		#region Static methods to access Entidad of a Relacion
		/// <summary>
		/// Gets a list of Entidad.
		/// </summary>
		[global::System.Diagnostics.DebuggerStepThrough]
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1011")]
		public static DslModeling::LinkedElementCollection<Entidad> GetEntidad(Relacion element)
		{
			return GetRoleCollection<DslModeling::LinkedElementCollection<Entidad>, Entidad>(element, RelacionDomainRoleId);
		}
		#endregion
		#region Relacion domain role code
		
		/// <summary>
		/// Relacion domain role Id.
		/// </summary>
		public static readonly global::System.Guid RelacionDomainRoleId = new global::System.Guid(0x31ad9191, 0x1381, 0x4176, 0x89, 0xf9, 0x7d, 0xcd, 0xfc, 0x03, 0x99, 0x46);
		
		/// <summary>
		/// DomainRole Relacion
		/// Description for UPM_IPS.XCYLSProyectoIPS.EntidadReferencesRelacioned.Relacion
		/// </summary>
		[DslDesign::DisplayNameResource("UPM_IPS.XCYLSProyectoIPS.EntidadReferencesRelacioned/Relacion.DisplayName", typeof(global::UPM_IPS.XCYLSProyectoIPS.XCYLSProyectoIPSDomainModel), "UPM_IPS.XCYLSProyectoIPS.GeneratedCode.DomainModelResx")]
		[DslDesign::DescriptionResource("UPM_IPS.XCYLSProyectoIPS.EntidadReferencesRelacioned/Relacion.Description", typeof(global::UPM_IPS.XCYLSProyectoIPS.XCYLSProyectoIPSDomainModel), "UPM_IPS.XCYLSProyectoIPS.GeneratedCode.DomainModelResx")]
		[DslModeling::DomainRole(DslModeling::DomainRoleOrder.Target, PropertyName = "Entidad", PropertyDisplayNameKey="UPM_IPS.XCYLSProyectoIPS.EntidadReferencesRelacioned/Relacion.PropertyDisplayName",  PropagatesCopy = DslModeling::PropagatesCopyOption.DoNotPropagateCopy, Multiplicity = DslModeling::Multiplicity.ZeroMany)]
		[DslModeling::DomainObjectId("31ad9191-1381-4176-89f9-7dcdfc039946")]
		public virtual Relacion Relacion
		{
			[global::System.Diagnostics.DebuggerStepThrough]
			get
			{
				return (Relacion)DslModeling::DomainRoleInfo.GetRolePlayer(this, RelacionDomainRoleId);
			}
			[global::System.Diagnostics.DebuggerStepThrough]
			set
			{
				DslModeling::DomainRoleInfo.SetRolePlayer(this, RelacionDomainRoleId, value);
			}
		}
				
		#endregion
		#region Static methods to access Relacioned of a Entidad
		/// <summary>
		/// Gets a list of Relacioned.
		/// </summary>
		[global::System.Diagnostics.DebuggerStepThrough]
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1011")]
		public static DslModeling::LinkedElementCollection<Relacion> GetRelacioned(Entidad element)
		{
			return GetRoleCollection<DslModeling::LinkedElementCollection<Relacion>, Relacion>(element, EntidadDomainRoleId);
		}
		#endregion
		#region Entidad link accessor
		/// <summary>
		/// Get the list of EntidadReferencesRelacioned links to a Entidad.
		/// </summary>
		[global::System.Diagnostics.DebuggerStepThrough]
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1011")]
		public static global::System.Collections.ObjectModel.ReadOnlyCollection<global::UPM_IPS.XCYLSProyectoIPS.EntidadReferencesRelacioned> GetLinksToRelacioned ( global::UPM_IPS.XCYLSProyectoIPS.Entidad entidadInstance )
		{
			return DslModeling::DomainRoleInfo.GetElementLinks<global::UPM_IPS.XCYLSProyectoIPS.EntidadReferencesRelacioned>(entidadInstance, global::UPM_IPS.XCYLSProyectoIPS.EntidadReferencesRelacioned.EntidadDomainRoleId);
		}
		#endregion
		#region Relacion link accessor
		/// <summary>
		/// Get the list of EntidadReferencesRelacioned links to a Relacion.
		/// </summary>
		[global::System.Diagnostics.DebuggerStepThrough]
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1011")]
		public static global::System.Collections.ObjectModel.ReadOnlyCollection<global::UPM_IPS.XCYLSProyectoIPS.EntidadReferencesRelacioned> GetLinksToEntidad ( global::UPM_IPS.XCYLSProyectoIPS.Relacion relacionInstance )
		{
			return DslModeling::DomainRoleInfo.GetElementLinks<global::UPM_IPS.XCYLSProyectoIPS.EntidadReferencesRelacioned>(relacionInstance, global::UPM_IPS.XCYLSProyectoIPS.EntidadReferencesRelacioned.RelacionDomainRoleId);
		}
		#endregion
		#region EntidadReferencesRelacioned instance accessors
		
		/// <summary>
		/// Get any EntidadReferencesRelacioned links between a given Entidad and a Relacion.
		/// </summary>
		[global::System.Diagnostics.DebuggerStepThrough]
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1011")]
		public static global::System.Collections.ObjectModel.ReadOnlyCollection<global::UPM_IPS.XCYLSProyectoIPS.EntidadReferencesRelacioned> GetLinks( global::UPM_IPS.XCYLSProyectoIPS.Entidad source, global::UPM_IPS.XCYLSProyectoIPS.Relacion target )
		{
			global::System.Collections.Generic.List<global::UPM_IPS.XCYLSProyectoIPS.EntidadReferencesRelacioned> outLinks = new global::System.Collections.Generic.List<global::UPM_IPS.XCYLSProyectoIPS.EntidadReferencesRelacioned>();
			global::System.Collections.Generic.IList<global::UPM_IPS.XCYLSProyectoIPS.EntidadReferencesRelacioned> links = DslModeling::DomainRoleInfo.GetElementLinks<global::UPM_IPS.XCYLSProyectoIPS.EntidadReferencesRelacioned>(source, global::UPM_IPS.XCYLSProyectoIPS.EntidadReferencesRelacioned.EntidadDomainRoleId);
			foreach ( global::UPM_IPS.XCYLSProyectoIPS.EntidadReferencesRelacioned link in links )
			{
				if ( target.Equals(link.Relacion) )
				{
					outLinks.Add(link);
				}
			}
			return outLinks.AsReadOnly();
		}
		/// <summary>
		/// Get the one EntidadReferencesRelacioned link between a given Entidadand a Relacion.
		/// </summary>
		[global::System.Diagnostics.DebuggerStepThrough]
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1011")]
		public static global::UPM_IPS.XCYLSProyectoIPS.EntidadReferencesRelacioned GetLink( global::UPM_IPS.XCYLSProyectoIPS.Entidad source, global::UPM_IPS.XCYLSProyectoIPS.Relacion target )
		{
			global::System.Collections.Generic.IList<global::UPM_IPS.XCYLSProyectoIPS.EntidadReferencesRelacioned> links = DslModeling::DomainRoleInfo.GetElementLinks<global::UPM_IPS.XCYLSProyectoIPS.EntidadReferencesRelacioned>(source, global::UPM_IPS.XCYLSProyectoIPS.EntidadReferencesRelacioned.EntidadDomainRoleId);
			foreach ( global::UPM_IPS.XCYLSProyectoIPS.EntidadReferencesRelacioned link in links )
			{
				if ( target.Equals(link.Relacion) )
				{
					return link;
				}
			}
			return null;
		}
		
		#endregion
	}
}
namespace UPM_IPS.XCYLSProyectoIPS
{
	/// <summary>
	/// DomainRelationship DeraWebIPSHasRelacioned
	/// Description for UPM_IPS.XCYLSProyectoIPS.DeraWebIPSHasRelacioned
	/// </summary>
	[DslDesign::DisplayNameResource("UPM_IPS.XCYLSProyectoIPS.DeraWebIPSHasRelacioned.DisplayName", typeof(global::UPM_IPS.XCYLSProyectoIPS.XCYLSProyectoIPSDomainModel), "UPM_IPS.XCYLSProyectoIPS.GeneratedCode.DomainModelResx")]
	[DslDesign::DescriptionResource("UPM_IPS.XCYLSProyectoIPS.DeraWebIPSHasRelacioned.Description", typeof(global::UPM_IPS.XCYLSProyectoIPS.XCYLSProyectoIPSDomainModel), "UPM_IPS.XCYLSProyectoIPS.GeneratedCode.DomainModelResx")]
	[DslModeling::DomainModelOwner(typeof(global::UPM_IPS.XCYLSProyectoIPS.XCYLSProyectoIPSDomainModel))]
	[global::System.CLSCompliant(true)]
	[DslModeling::DomainRelationship(IsEmbedding=true)]
	[DslModeling::DomainObjectId("6e3e5617-1ac7-4a23-84e6-b0b8e5019708")]
	public partial class DeraWebIPSHasRelacioned : DslModeling::ElementLink
	{
		#region Constructors, domain class Id
		
		/// <summary>
		/// DeraWebIPSHasRelacioned domain class Id.
		/// </summary>
		public static readonly new global::System.Guid DomainClassId = new global::System.Guid(0x6e3e5617, 0x1ac7, 0x4a23, 0x84, 0xe6, 0xb0, 0xb8, 0xe5, 0x01, 0x97, 0x08);
	
				
		/// <summary>
		/// Constructor
		/// Creates a DeraWebIPSHasRelacioned link in the same Partition as the given DeraWebIPS
		/// </summary>
		/// <param name="source">DeraWebIPS to use as the source of the relationship.</param>
		/// <param name="target">Relacion to use as the target of the relationship.</param>
		public DeraWebIPSHasRelacioned(DeraWebIPS source, Relacion target)
			: base((source != null ? source.Partition : null), new DslModeling::RoleAssignment[]{new DslModeling::RoleAssignment(DeraWebIPSHasRelacioned.DeraWebIPSDomainRoleId, source), new DslModeling::RoleAssignment(DeraWebIPSHasRelacioned.RelacionDomainRoleId, target)}, null)
		{
		}
		
		/// <summary>
		/// Constructor
		/// </summary>
		/// <param name="store">Store where new link is to be created.</param>
		/// <param name="roleAssignments">List of relationship role assignments.</param>
		public DeraWebIPSHasRelacioned(DslModeling::Store store, params DslModeling::RoleAssignment[] roleAssignments)
			: base(store != null ? store.DefaultPartitionForClass(DomainClassId) : null, roleAssignments, null)
		{
		}
		
		/// <summary>
		/// Constructor
		/// </summary>
		/// <param name="store">Store where new link is to be created.</param>
		/// <param name="roleAssignments">List of relationship role assignments.</param>
		/// <param name="propertyAssignments">List of properties assignments to set on the new link.</param>
		public DeraWebIPSHasRelacioned(DslModeling::Store store, DslModeling::RoleAssignment[] roleAssignments, DslModeling::PropertyAssignment[] propertyAssignments)
			: base(store != null ? store.DefaultPartitionForClass(DomainClassId) : null, roleAssignments, propertyAssignments)
		{
		}
		
		/// <summary>
		/// Constructor
		/// </summary>
		/// <param name="partition">Partition where new link is to be created.</param>
		/// <param name="roleAssignments">List of relationship role assignments.</param>
		public DeraWebIPSHasRelacioned(DslModeling::Partition partition, params DslModeling::RoleAssignment[] roleAssignments)
			: base(partition, roleAssignments, null)
		{
		}
		
		/// <summary>
		/// Constructor
		/// </summary>
		/// <param name="partition">Partition where new link is to be created.</param>
		/// <param name="roleAssignments">List of relationship role assignments.</param>
		/// <param name="propertyAssignments">List of properties assignments to set on the new link.</param>
		public DeraWebIPSHasRelacioned(DslModeling::Partition partition, DslModeling::RoleAssignment[] roleAssignments, DslModeling::PropertyAssignment[] propertyAssignments)
			: base(partition, roleAssignments, propertyAssignments)
		{
		}
		#endregion
		#region DeraWebIPS domain role code
		
		/// <summary>
		/// DeraWebIPS domain role Id.
		/// </summary>
		public static readonly global::System.Guid DeraWebIPSDomainRoleId = new global::System.Guid(0xbe9891ff, 0xb02f, 0x4fdd, 0x97, 0xe9, 0x2c, 0xdf, 0xb9, 0xdf, 0x0b, 0x44);
		
		/// <summary>
		/// DomainRole DeraWebIPS
		/// Description for UPM_IPS.XCYLSProyectoIPS.DeraWebIPSHasRelacioned.DeraWebIPS
		/// </summary>
		[DslDesign::DisplayNameResource("UPM_IPS.XCYLSProyectoIPS.DeraWebIPSHasRelacioned/DeraWebIPS.DisplayName", typeof(global::UPM_IPS.XCYLSProyectoIPS.XCYLSProyectoIPSDomainModel), "UPM_IPS.XCYLSProyectoIPS.GeneratedCode.DomainModelResx")]
		[DslDesign::DescriptionResource("UPM_IPS.XCYLSProyectoIPS.DeraWebIPSHasRelacioned/DeraWebIPS.Description", typeof(global::UPM_IPS.XCYLSProyectoIPS.XCYLSProyectoIPSDomainModel), "UPM_IPS.XCYLSProyectoIPS.GeneratedCode.DomainModelResx")]
		[DslModeling::DomainRole(DslModeling::DomainRoleOrder.Source, PropertyName = "Relacioned", PropertyDisplayNameKey="UPM_IPS.XCYLSProyectoIPS.DeraWebIPSHasRelacioned/DeraWebIPS.PropertyDisplayName",  PropagatesCopy = DslModeling::PropagatesCopyOption.PropagatesCopyToLinkAndOppositeRolePlayer, Multiplicity = DslModeling::Multiplicity.ZeroMany)]
		[DslModeling::DomainObjectId("be9891ff-b02f-4fdd-97e9-2cdfb9df0b44")]
		public virtual DeraWebIPS DeraWebIPS
		{
			[global::System.Diagnostics.DebuggerStepThrough]
			get
			{
				return (DeraWebIPS)DslModeling::DomainRoleInfo.GetRolePlayer(this, DeraWebIPSDomainRoleId);
			}
			[global::System.Diagnostics.DebuggerStepThrough]
			set
			{
				DslModeling::DomainRoleInfo.SetRolePlayer(this, DeraWebIPSDomainRoleId, value);
			}
		}
				
		#endregion
		#region Static methods to access DeraWebIPS of a Relacion
		/// <summary>
		/// Gets DeraWebIPS.
		/// </summary>
		[global::System.Diagnostics.DebuggerStepThrough]
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1011")]
		public static DeraWebIPS GetDeraWebIPS(Relacion element)
		{
			return DslModeling::DomainRoleInfo.GetLinkedElement(element, RelacionDomainRoleId) as DeraWebIPS;
		}
		
		/// <summary>
		/// Sets DeraWebIPS.
		/// </summary>
		[global::System.Diagnostics.DebuggerStepThrough]
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1011")]
		public static void SetDeraWebIPS(Relacion element, DeraWebIPS newDeraWebIPS)
		{
			DslModeling::DomainRoleInfo.SetLinkedElement(element, RelacionDomainRoleId, newDeraWebIPS);
		}
		#endregion
		#region Relacion domain role code
		
		/// <summary>
		/// Relacion domain role Id.
		/// </summary>
		public static readonly global::System.Guid RelacionDomainRoleId = new global::System.Guid(0x36b327d4, 0x8e3f, 0x4dd3, 0x84, 0x58, 0x21, 0x80, 0x45, 0x70, 0xb1, 0x84);
		
		/// <summary>
		/// DomainRole Relacion
		/// Description for UPM_IPS.XCYLSProyectoIPS.DeraWebIPSHasRelacioned.Relacion
		/// </summary>
		[DslDesign::DisplayNameResource("UPM_IPS.XCYLSProyectoIPS.DeraWebIPSHasRelacioned/Relacion.DisplayName", typeof(global::UPM_IPS.XCYLSProyectoIPS.XCYLSProyectoIPSDomainModel), "UPM_IPS.XCYLSProyectoIPS.GeneratedCode.DomainModelResx")]
		[DslDesign::DescriptionResource("UPM_IPS.XCYLSProyectoIPS.DeraWebIPSHasRelacioned/Relacion.Description", typeof(global::UPM_IPS.XCYLSProyectoIPS.XCYLSProyectoIPSDomainModel), "UPM_IPS.XCYLSProyectoIPS.GeneratedCode.DomainModelResx")]
		[DslModeling::DomainRole(DslModeling::DomainRoleOrder.Target, PropertyName = "DeraWebIPS", PropertyDisplayNameKey="UPM_IPS.XCYLSProyectoIPS.DeraWebIPSHasRelacioned/Relacion.PropertyDisplayName", PropagatesDelete = true,  PropagatesCopy = DslModeling::PropagatesCopyOption.DoNotPropagateCopy, Multiplicity = DslModeling::Multiplicity.One)]
		[DslModeling::DomainObjectId("36b327d4-8e3f-4dd3-8458-21804570b184")]
		public virtual Relacion Relacion
		{
			[global::System.Diagnostics.DebuggerStepThrough]
			get
			{
				return (Relacion)DslModeling::DomainRoleInfo.GetRolePlayer(this, RelacionDomainRoleId);
			}
			[global::System.Diagnostics.DebuggerStepThrough]
			set
			{
				DslModeling::DomainRoleInfo.SetRolePlayer(this, RelacionDomainRoleId, value);
			}
		}
				
		#endregion
		#region Static methods to access Relacioned of a DeraWebIPS
		/// <summary>
		/// Gets a list of Relacioned.
		/// </summary>
		[global::System.Diagnostics.DebuggerStepThrough]
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1011")]
		public static DslModeling::LinkedElementCollection<Relacion> GetRelacioned(DeraWebIPS element)
		{
			return GetRoleCollection<DslModeling::LinkedElementCollection<Relacion>, Relacion>(element, DeraWebIPSDomainRoleId);
		}
		#endregion
		#region DeraWebIPS link accessor
		/// <summary>
		/// Get the list of DeraWebIPSHasRelacioned links to a DeraWebIPS.
		/// </summary>
		[global::System.Diagnostics.DebuggerStepThrough]
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1011")]
		public static global::System.Collections.ObjectModel.ReadOnlyCollection<global::UPM_IPS.XCYLSProyectoIPS.DeraWebIPSHasRelacioned> GetLinksToRelacioned ( global::UPM_IPS.XCYLSProyectoIPS.DeraWebIPS deraWebIPSInstance )
		{
			return DslModeling::DomainRoleInfo.GetElementLinks<global::UPM_IPS.XCYLSProyectoIPS.DeraWebIPSHasRelacioned>(deraWebIPSInstance, global::UPM_IPS.XCYLSProyectoIPS.DeraWebIPSHasRelacioned.DeraWebIPSDomainRoleId);
		}
		#endregion
		#region Relacion link accessor
		/// <summary>
		/// Get the DeraWebIPSHasRelacioned link to a Relacion.
		/// </summary>
		[global::System.Diagnostics.DebuggerStepThrough]
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1011")]
		public static global::UPM_IPS.XCYLSProyectoIPS.DeraWebIPSHasRelacioned GetLinkToDeraWebIPS (global::UPM_IPS.XCYLSProyectoIPS.Relacion relacionInstance)
		{
			global::System.Collections.Generic.IList<global::UPM_IPS.XCYLSProyectoIPS.DeraWebIPSHasRelacioned> links = DslModeling::DomainRoleInfo.GetElementLinks<global::UPM_IPS.XCYLSProyectoIPS.DeraWebIPSHasRelacioned>(relacionInstance, global::UPM_IPS.XCYLSProyectoIPS.DeraWebIPSHasRelacioned.RelacionDomainRoleId);
			global::System.Diagnostics.Debug.Assert(links.Count <= 1, "Multiplicity of Relacion not obeyed.");
			if ( links.Count == 0 )
			{
				return null;
			}
			else
			{
				return links[0];
			}
		}
		#endregion
		#region DeraWebIPSHasRelacioned instance accessors
		
		/// <summary>
		/// Get any DeraWebIPSHasRelacioned links between a given DeraWebIPS and a Relacion.
		/// </summary>
		[global::System.Diagnostics.DebuggerStepThrough]
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1011")]
		public static global::System.Collections.ObjectModel.ReadOnlyCollection<global::UPM_IPS.XCYLSProyectoIPS.DeraWebIPSHasRelacioned> GetLinks( global::UPM_IPS.XCYLSProyectoIPS.DeraWebIPS source, global::UPM_IPS.XCYLSProyectoIPS.Relacion target )
		{
			global::System.Collections.Generic.List<global::UPM_IPS.XCYLSProyectoIPS.DeraWebIPSHasRelacioned> outLinks = new global::System.Collections.Generic.List<global::UPM_IPS.XCYLSProyectoIPS.DeraWebIPSHasRelacioned>();
			global::System.Collections.Generic.IList<global::UPM_IPS.XCYLSProyectoIPS.DeraWebIPSHasRelacioned> links = DslModeling::DomainRoleInfo.GetElementLinks<global::UPM_IPS.XCYLSProyectoIPS.DeraWebIPSHasRelacioned>(source, global::UPM_IPS.XCYLSProyectoIPS.DeraWebIPSHasRelacioned.DeraWebIPSDomainRoleId);
			foreach ( global::UPM_IPS.XCYLSProyectoIPS.DeraWebIPSHasRelacioned link in links )
			{
				if ( target.Equals(link.Relacion) )
				{
					outLinks.Add(link);
				}
			}
			return outLinks.AsReadOnly();
		}
		/// <summary>
		/// Get the one DeraWebIPSHasRelacioned link between a given DeraWebIPSand a Relacion.
		/// </summary>
		[global::System.Diagnostics.DebuggerStepThrough]
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1011")]
		public static global::UPM_IPS.XCYLSProyectoIPS.DeraWebIPSHasRelacioned GetLink( global::UPM_IPS.XCYLSProyectoIPS.DeraWebIPS source, global::UPM_IPS.XCYLSProyectoIPS.Relacion target )
		{
			global::System.Collections.Generic.IList<global::UPM_IPS.XCYLSProyectoIPS.DeraWebIPSHasRelacioned> links = DslModeling::DomainRoleInfo.GetElementLinks<global::UPM_IPS.XCYLSProyectoIPS.DeraWebIPSHasRelacioned>(source, global::UPM_IPS.XCYLSProyectoIPS.DeraWebIPSHasRelacioned.DeraWebIPSDomainRoleId);
			foreach ( global::UPM_IPS.XCYLSProyectoIPS.DeraWebIPSHasRelacioned link in links )
			{
				if ( target.Equals(link.Relacion) )
				{
					return link;
				}
			}
			return null;
		}
		
		#endregion
	}
}
namespace UPM_IPS.XCYLSProyectoIPS
{
	/// <summary>
	/// DomainRelationship EntidadHasAtributoEntidad
	/// Description for UPM_IPS.XCYLSProyectoIPS.EntidadHasAtributoEntidad
	/// </summary>
	[DslDesign::DisplayNameResource("UPM_IPS.XCYLSProyectoIPS.EntidadHasAtributoEntidad.DisplayName", typeof(global::UPM_IPS.XCYLSProyectoIPS.XCYLSProyectoIPSDomainModel), "UPM_IPS.XCYLSProyectoIPS.GeneratedCode.DomainModelResx")]
	[DslDesign::DescriptionResource("UPM_IPS.XCYLSProyectoIPS.EntidadHasAtributoEntidad.Description", typeof(global::UPM_IPS.XCYLSProyectoIPS.XCYLSProyectoIPSDomainModel), "UPM_IPS.XCYLSProyectoIPS.GeneratedCode.DomainModelResx")]
	[DslModeling::DomainModelOwner(typeof(global::UPM_IPS.XCYLSProyectoIPS.XCYLSProyectoIPSDomainModel))]
	[global::System.CLSCompliant(true)]
	[DslModeling::DomainRelationship(IsEmbedding=true)]
	[DslModeling::DomainObjectId("c49771df-3545-4419-8653-bb45e7acbf9a")]
	public partial class EntidadHasAtributoEntidad : DslModeling::ElementLink
	{
		#region Constructors, domain class Id
		
		/// <summary>
		/// EntidadHasAtributoEntidad domain class Id.
		/// </summary>
		public static readonly new global::System.Guid DomainClassId = new global::System.Guid(0xc49771df, 0x3545, 0x4419, 0x86, 0x53, 0xbb, 0x45, 0xe7, 0xac, 0xbf, 0x9a);
	
				
		/// <summary>
		/// Constructor
		/// Creates a EntidadHasAtributoEntidad link in the same Partition as the given Entidad
		/// </summary>
		/// <param name="source">Entidad to use as the source of the relationship.</param>
		/// <param name="target">AtributoEntidad to use as the target of the relationship.</param>
		public EntidadHasAtributoEntidad(Entidad source, AtributoEntidad target)
			: base((source != null ? source.Partition : null), new DslModeling::RoleAssignment[]{new DslModeling::RoleAssignment(EntidadHasAtributoEntidad.EntidadDomainRoleId, source), new DslModeling::RoleAssignment(EntidadHasAtributoEntidad.AtributoEntidadDomainRoleId, target)}, null)
		{
		}
		
		/// <summary>
		/// Constructor
		/// </summary>
		/// <param name="store">Store where new link is to be created.</param>
		/// <param name="roleAssignments">List of relationship role assignments.</param>
		public EntidadHasAtributoEntidad(DslModeling::Store store, params DslModeling::RoleAssignment[] roleAssignments)
			: base(store != null ? store.DefaultPartitionForClass(DomainClassId) : null, roleAssignments, null)
		{
		}
		
		/// <summary>
		/// Constructor
		/// </summary>
		/// <param name="store">Store where new link is to be created.</param>
		/// <param name="roleAssignments">List of relationship role assignments.</param>
		/// <param name="propertyAssignments">List of properties assignments to set on the new link.</param>
		public EntidadHasAtributoEntidad(DslModeling::Store store, DslModeling::RoleAssignment[] roleAssignments, DslModeling::PropertyAssignment[] propertyAssignments)
			: base(store != null ? store.DefaultPartitionForClass(DomainClassId) : null, roleAssignments, propertyAssignments)
		{
		}
		
		/// <summary>
		/// Constructor
		/// </summary>
		/// <param name="partition">Partition where new link is to be created.</param>
		/// <param name="roleAssignments">List of relationship role assignments.</param>
		public EntidadHasAtributoEntidad(DslModeling::Partition partition, params DslModeling::RoleAssignment[] roleAssignments)
			: base(partition, roleAssignments, null)
		{
		}
		
		/// <summary>
		/// Constructor
		/// </summary>
		/// <param name="partition">Partition where new link is to be created.</param>
		/// <param name="roleAssignments">List of relationship role assignments.</param>
		/// <param name="propertyAssignments">List of properties assignments to set on the new link.</param>
		public EntidadHasAtributoEntidad(DslModeling::Partition partition, DslModeling::RoleAssignment[] roleAssignments, DslModeling::PropertyAssignment[] propertyAssignments)
			: base(partition, roleAssignments, propertyAssignments)
		{
		}
		#endregion
		#region Entidad domain role code
		
		/// <summary>
		/// Entidad domain role Id.
		/// </summary>
		public static readonly global::System.Guid EntidadDomainRoleId = new global::System.Guid(0x2df428cf, 0xb88b, 0x4e13, 0x86, 0x6f, 0x21, 0x56, 0x0f, 0x48, 0x14, 0x8a);
		
		/// <summary>
		/// DomainRole Entidad
		/// Description for UPM_IPS.XCYLSProyectoIPS.EntidadHasAtributoEntidad.Entidad
		/// </summary>
		[DslDesign::DisplayNameResource("UPM_IPS.XCYLSProyectoIPS.EntidadHasAtributoEntidad/Entidad.DisplayName", typeof(global::UPM_IPS.XCYLSProyectoIPS.XCYLSProyectoIPSDomainModel), "UPM_IPS.XCYLSProyectoIPS.GeneratedCode.DomainModelResx")]
		[DslDesign::DescriptionResource("UPM_IPS.XCYLSProyectoIPS.EntidadHasAtributoEntidad/Entidad.Description", typeof(global::UPM_IPS.XCYLSProyectoIPS.XCYLSProyectoIPSDomainModel), "UPM_IPS.XCYLSProyectoIPS.GeneratedCode.DomainModelResx")]
		[DslModeling::DomainRole(DslModeling::DomainRoleOrder.Source, PropertyName = "AtributoEntidad", PropertyDisplayNameKey="UPM_IPS.XCYLSProyectoIPS.EntidadHasAtributoEntidad/Entidad.PropertyDisplayName",  PropagatesCopy = DslModeling::PropagatesCopyOption.PropagatesCopyToLinkAndOppositeRolePlayer, Multiplicity = DslModeling::Multiplicity.ZeroMany)]
		[DslModeling::DomainObjectId("2df428cf-b88b-4e13-866f-21560f48148a")]
		public virtual Entidad Entidad
		{
			[global::System.Diagnostics.DebuggerStepThrough]
			get
			{
				return (Entidad)DslModeling::DomainRoleInfo.GetRolePlayer(this, EntidadDomainRoleId);
			}
			[global::System.Diagnostics.DebuggerStepThrough]
			set
			{
				DslModeling::DomainRoleInfo.SetRolePlayer(this, EntidadDomainRoleId, value);
			}
		}
				
		#endregion
		#region Static methods to access Entidad of a AtributoEntidad
		/// <summary>
		/// Gets Entidad.
		/// </summary>
		[global::System.Diagnostics.DebuggerStepThrough]
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1011")]
		public static Entidad GetEntidad(AtributoEntidad element)
		{
			return DslModeling::DomainRoleInfo.GetLinkedElement(element, AtributoEntidadDomainRoleId) as Entidad;
		}
		
		/// <summary>
		/// Sets Entidad.
		/// </summary>
		[global::System.Diagnostics.DebuggerStepThrough]
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1011")]
		public static void SetEntidad(AtributoEntidad element, Entidad newEntidad)
		{
			DslModeling::DomainRoleInfo.SetLinkedElement(element, AtributoEntidadDomainRoleId, newEntidad);
		}
		#endregion
		#region AtributoEntidad domain role code
		
		/// <summary>
		/// AtributoEntidad domain role Id.
		/// </summary>
		public static readonly global::System.Guid AtributoEntidadDomainRoleId = new global::System.Guid(0xba4c9d44, 0x66f8, 0x406c, 0x9b, 0xb8, 0xdc, 0x45, 0xf4, 0x93, 0x63, 0x3e);
		
		/// <summary>
		/// DomainRole AtributoEntidad
		/// Description for
		/// UPM_IPS.XCYLSProyectoIPS.EntidadHasAtributoEntidad.AtributoEntidad
		/// </summary>
		[DslDesign::DisplayNameResource("UPM_IPS.XCYLSProyectoIPS.EntidadHasAtributoEntidad/AtributoEntidad.DisplayName", typeof(global::UPM_IPS.XCYLSProyectoIPS.XCYLSProyectoIPSDomainModel), "UPM_IPS.XCYLSProyectoIPS.GeneratedCode.DomainModelResx")]
		[DslDesign::DescriptionResource("UPM_IPS.XCYLSProyectoIPS.EntidadHasAtributoEntidad/AtributoEntidad.Description", typeof(global::UPM_IPS.XCYLSProyectoIPS.XCYLSProyectoIPSDomainModel), "UPM_IPS.XCYLSProyectoIPS.GeneratedCode.DomainModelResx")]
		[DslModeling::DomainRole(DslModeling::DomainRoleOrder.Target, PropertyName = "Entidad", PropertyDisplayNameKey="UPM_IPS.XCYLSProyectoIPS.EntidadHasAtributoEntidad/AtributoEntidad.PropertyDisplayName", PropagatesDelete = true,  PropagatesCopy = DslModeling::PropagatesCopyOption.DoNotPropagateCopy, Multiplicity = DslModeling::Multiplicity.One)]
		[DslModeling::DomainObjectId("ba4c9d44-66f8-406c-9bb8-dc45f493633e")]
		public virtual AtributoEntidad AtributoEntidad
		{
			[global::System.Diagnostics.DebuggerStepThrough]
			get
			{
				return (AtributoEntidad)DslModeling::DomainRoleInfo.GetRolePlayer(this, AtributoEntidadDomainRoleId);
			}
			[global::System.Diagnostics.DebuggerStepThrough]
			set
			{
				DslModeling::DomainRoleInfo.SetRolePlayer(this, AtributoEntidadDomainRoleId, value);
			}
		}
				
		#endregion
		#region Static methods to access AtributoEntidad of a Entidad
		/// <summary>
		/// Gets a list of AtributoEntidad.
		/// </summary>
		[global::System.Diagnostics.DebuggerStepThrough]
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1011")]
		public static DslModeling::LinkedElementCollection<AtributoEntidad> GetAtributoEntidad(Entidad element)
		{
			return GetRoleCollection<DslModeling::LinkedElementCollection<AtributoEntidad>, AtributoEntidad>(element, EntidadDomainRoleId);
		}
		#endregion
		#region Entidad link accessor
		/// <summary>
		/// Get the list of EntidadHasAtributoEntidad links to a Entidad.
		/// </summary>
		[global::System.Diagnostics.DebuggerStepThrough]
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1011")]
		public static global::System.Collections.ObjectModel.ReadOnlyCollection<global::UPM_IPS.XCYLSProyectoIPS.EntidadHasAtributoEntidad> GetLinksToAtributoEntidad ( global::UPM_IPS.XCYLSProyectoIPS.Entidad entidadInstance )
		{
			return DslModeling::DomainRoleInfo.GetElementLinks<global::UPM_IPS.XCYLSProyectoIPS.EntidadHasAtributoEntidad>(entidadInstance, global::UPM_IPS.XCYLSProyectoIPS.EntidadHasAtributoEntidad.EntidadDomainRoleId);
		}
		#endregion
		#region AtributoEntidad link accessor
		/// <summary>
		/// Get the EntidadHasAtributoEntidad link to a AtributoEntidad.
		/// </summary>
		[global::System.Diagnostics.DebuggerStepThrough]
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1011")]
		public static global::UPM_IPS.XCYLSProyectoIPS.EntidadHasAtributoEntidad GetLinkToEntidad (global::UPM_IPS.XCYLSProyectoIPS.AtributoEntidad atributoEntidadInstance)
		{
			global::System.Collections.Generic.IList<global::UPM_IPS.XCYLSProyectoIPS.EntidadHasAtributoEntidad> links = DslModeling::DomainRoleInfo.GetElementLinks<global::UPM_IPS.XCYLSProyectoIPS.EntidadHasAtributoEntidad>(atributoEntidadInstance, global::UPM_IPS.XCYLSProyectoIPS.EntidadHasAtributoEntidad.AtributoEntidadDomainRoleId);
			global::System.Diagnostics.Debug.Assert(links.Count <= 1, "Multiplicity of AtributoEntidad not obeyed.");
			if ( links.Count == 0 )
			{
				return null;
			}
			else
			{
				return links[0];
			}
		}
		#endregion
		#region EntidadHasAtributoEntidad instance accessors
		
		/// <summary>
		/// Get any EntidadHasAtributoEntidad links between a given Entidad and a AtributoEntidad.
		/// </summary>
		[global::System.Diagnostics.DebuggerStepThrough]
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1011")]
		public static global::System.Collections.ObjectModel.ReadOnlyCollection<global::UPM_IPS.XCYLSProyectoIPS.EntidadHasAtributoEntidad> GetLinks( global::UPM_IPS.XCYLSProyectoIPS.Entidad source, global::UPM_IPS.XCYLSProyectoIPS.AtributoEntidad target )
		{
			global::System.Collections.Generic.List<global::UPM_IPS.XCYLSProyectoIPS.EntidadHasAtributoEntidad> outLinks = new global::System.Collections.Generic.List<global::UPM_IPS.XCYLSProyectoIPS.EntidadHasAtributoEntidad>();
			global::System.Collections.Generic.IList<global::UPM_IPS.XCYLSProyectoIPS.EntidadHasAtributoEntidad> links = DslModeling::DomainRoleInfo.GetElementLinks<global::UPM_IPS.XCYLSProyectoIPS.EntidadHasAtributoEntidad>(source, global::UPM_IPS.XCYLSProyectoIPS.EntidadHasAtributoEntidad.EntidadDomainRoleId);
			foreach ( global::UPM_IPS.XCYLSProyectoIPS.EntidadHasAtributoEntidad link in links )
			{
				if ( target.Equals(link.AtributoEntidad) )
				{
					outLinks.Add(link);
				}
			}
			return outLinks.AsReadOnly();
		}
		/// <summary>
		/// Get the one EntidadHasAtributoEntidad link between a given Entidadand a AtributoEntidad.
		/// </summary>
		[global::System.Diagnostics.DebuggerStepThrough]
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1011")]
		public static global::UPM_IPS.XCYLSProyectoIPS.EntidadHasAtributoEntidad GetLink( global::UPM_IPS.XCYLSProyectoIPS.Entidad source, global::UPM_IPS.XCYLSProyectoIPS.AtributoEntidad target )
		{
			global::System.Collections.Generic.IList<global::UPM_IPS.XCYLSProyectoIPS.EntidadHasAtributoEntidad> links = DslModeling::DomainRoleInfo.GetElementLinks<global::UPM_IPS.XCYLSProyectoIPS.EntidadHasAtributoEntidad>(source, global::UPM_IPS.XCYLSProyectoIPS.EntidadHasAtributoEntidad.EntidadDomainRoleId);
			foreach ( global::UPM_IPS.XCYLSProyectoIPS.EntidadHasAtributoEntidad link in links )
			{
				if ( target.Equals(link.AtributoEntidad) )
				{
					return link;
				}
			}
			return null;
		}
		
		#endregion
	}
}
namespace UPM_IPS.XCYLSProyectoIPS
{
	/// <summary>
	/// DomainRelationship RelacionHasAtributoRelacioned
	/// Description for UPM_IPS.XCYLSProyectoIPS.RelacionHasAtributoRelacioned
	/// </summary>
	[DslDesign::DisplayNameResource("UPM_IPS.XCYLSProyectoIPS.RelacionHasAtributoRelacioned.DisplayName", typeof(global::UPM_IPS.XCYLSProyectoIPS.XCYLSProyectoIPSDomainModel), "UPM_IPS.XCYLSProyectoIPS.GeneratedCode.DomainModelResx")]
	[DslDesign::DescriptionResource("UPM_IPS.XCYLSProyectoIPS.RelacionHasAtributoRelacioned.Description", typeof(global::UPM_IPS.XCYLSProyectoIPS.XCYLSProyectoIPSDomainModel), "UPM_IPS.XCYLSProyectoIPS.GeneratedCode.DomainModelResx")]
	[DslModeling::DomainModelOwner(typeof(global::UPM_IPS.XCYLSProyectoIPS.XCYLSProyectoIPSDomainModel))]
	[global::System.CLSCompliant(true)]
	[DslModeling::DomainRelationship(IsEmbedding=true)]
	[DslModeling::DomainObjectId("6fbcd0ba-6f45-4f67-8cec-07412792afee")]
	public partial class RelacionHasAtributoRelacioned : DslModeling::ElementLink
	{
		#region Constructors, domain class Id
		
		/// <summary>
		/// RelacionHasAtributoRelacioned domain class Id.
		/// </summary>
		public static readonly new global::System.Guid DomainClassId = new global::System.Guid(0x6fbcd0ba, 0x6f45, 0x4f67, 0x8c, 0xec, 0x07, 0x41, 0x27, 0x92, 0xaf, 0xee);
	
				
		/// <summary>
		/// Constructor
		/// Creates a RelacionHasAtributoRelacioned link in the same Partition as the given Relacion
		/// </summary>
		/// <param name="source">Relacion to use as the source of the relationship.</param>
		/// <param name="target">AtributoRelacion to use as the target of the relationship.</param>
		public RelacionHasAtributoRelacioned(Relacion source, AtributoRelacion target)
			: base((source != null ? source.Partition : null), new DslModeling::RoleAssignment[]{new DslModeling::RoleAssignment(RelacionHasAtributoRelacioned.RelacionDomainRoleId, source), new DslModeling::RoleAssignment(RelacionHasAtributoRelacioned.AtributoRelacionDomainRoleId, target)}, null)
		{
		}
		
		/// <summary>
		/// Constructor
		/// </summary>
		/// <param name="store">Store where new link is to be created.</param>
		/// <param name="roleAssignments">List of relationship role assignments.</param>
		public RelacionHasAtributoRelacioned(DslModeling::Store store, params DslModeling::RoleAssignment[] roleAssignments)
			: base(store != null ? store.DefaultPartitionForClass(DomainClassId) : null, roleAssignments, null)
		{
		}
		
		/// <summary>
		/// Constructor
		/// </summary>
		/// <param name="store">Store where new link is to be created.</param>
		/// <param name="roleAssignments">List of relationship role assignments.</param>
		/// <param name="propertyAssignments">List of properties assignments to set on the new link.</param>
		public RelacionHasAtributoRelacioned(DslModeling::Store store, DslModeling::RoleAssignment[] roleAssignments, DslModeling::PropertyAssignment[] propertyAssignments)
			: base(store != null ? store.DefaultPartitionForClass(DomainClassId) : null, roleAssignments, propertyAssignments)
		{
		}
		
		/// <summary>
		/// Constructor
		/// </summary>
		/// <param name="partition">Partition where new link is to be created.</param>
		/// <param name="roleAssignments">List of relationship role assignments.</param>
		public RelacionHasAtributoRelacioned(DslModeling::Partition partition, params DslModeling::RoleAssignment[] roleAssignments)
			: base(partition, roleAssignments, null)
		{
		}
		
		/// <summary>
		/// Constructor
		/// </summary>
		/// <param name="partition">Partition where new link is to be created.</param>
		/// <param name="roleAssignments">List of relationship role assignments.</param>
		/// <param name="propertyAssignments">List of properties assignments to set on the new link.</param>
		public RelacionHasAtributoRelacioned(DslModeling::Partition partition, DslModeling::RoleAssignment[] roleAssignments, DslModeling::PropertyAssignment[] propertyAssignments)
			: base(partition, roleAssignments, propertyAssignments)
		{
		}
		#endregion
		#region Relacion domain role code
		
		/// <summary>
		/// Relacion domain role Id.
		/// </summary>
		public static readonly global::System.Guid RelacionDomainRoleId = new global::System.Guid(0x320ce5fb, 0x5757, 0x4793, 0xa3, 0x57, 0x1a, 0x22, 0xd3, 0x6f, 0xae, 0x80);
		
		/// <summary>
		/// DomainRole Relacion
		/// Description for UPM_IPS.XCYLSProyectoIPS.RelacionHasAtributoRelacioned.Relacion
		/// </summary>
		[DslDesign::DisplayNameResource("UPM_IPS.XCYLSProyectoIPS.RelacionHasAtributoRelacioned/Relacion.DisplayName", typeof(global::UPM_IPS.XCYLSProyectoIPS.XCYLSProyectoIPSDomainModel), "UPM_IPS.XCYLSProyectoIPS.GeneratedCode.DomainModelResx")]
		[DslDesign::DescriptionResource("UPM_IPS.XCYLSProyectoIPS.RelacionHasAtributoRelacioned/Relacion.Description", typeof(global::UPM_IPS.XCYLSProyectoIPS.XCYLSProyectoIPSDomainModel), "UPM_IPS.XCYLSProyectoIPS.GeneratedCode.DomainModelResx")]
		[DslModeling::DomainRole(DslModeling::DomainRoleOrder.Source, PropertyName = "AtributoRelacioned", PropertyDisplayNameKey="UPM_IPS.XCYLSProyectoIPS.RelacionHasAtributoRelacioned/Relacion.PropertyDisplayName",  PropagatesCopy = DslModeling::PropagatesCopyOption.PropagatesCopyToLinkAndOppositeRolePlayer, Multiplicity = DslModeling::Multiplicity.ZeroMany)]
		[DslModeling::DomainObjectId("320ce5fb-5757-4793-a357-1a22d36fae80")]
		public virtual Relacion Relacion
		{
			[global::System.Diagnostics.DebuggerStepThrough]
			get
			{
				return (Relacion)DslModeling::DomainRoleInfo.GetRolePlayer(this, RelacionDomainRoleId);
			}
			[global::System.Diagnostics.DebuggerStepThrough]
			set
			{
				DslModeling::DomainRoleInfo.SetRolePlayer(this, RelacionDomainRoleId, value);
			}
		}
				
		#endregion
		#region Static methods to access Relacion of a AtributoRelacion
		/// <summary>
		/// Gets Relacion.
		/// </summary>
		[global::System.Diagnostics.DebuggerStepThrough]
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1011")]
		public static Relacion GetRelacion(AtributoRelacion element)
		{
			return DslModeling::DomainRoleInfo.GetLinkedElement(element, AtributoRelacionDomainRoleId) as Relacion;
		}
		
		/// <summary>
		/// Sets Relacion.
		/// </summary>
		[global::System.Diagnostics.DebuggerStepThrough]
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1011")]
		public static void SetRelacion(AtributoRelacion element, Relacion newRelacion)
		{
			DslModeling::DomainRoleInfo.SetLinkedElement(element, AtributoRelacionDomainRoleId, newRelacion);
		}
		#endregion
		#region AtributoRelacion domain role code
		
		/// <summary>
		/// AtributoRelacion domain role Id.
		/// </summary>
		public static readonly global::System.Guid AtributoRelacionDomainRoleId = new global::System.Guid(0x91ce5276, 0xcd6d, 0x4d8c, 0x99, 0x8d, 0xbb, 0x78, 0x63, 0x1a, 0x61, 0xbb);
		
		/// <summary>
		/// DomainRole AtributoRelacion
		/// Description for
		/// UPM_IPS.XCYLSProyectoIPS.RelacionHasAtributoRelacioned.AtributoRelacion
		/// </summary>
		[DslDesign::DisplayNameResource("UPM_IPS.XCYLSProyectoIPS.RelacionHasAtributoRelacioned/AtributoRelacion.DisplayName", typeof(global::UPM_IPS.XCYLSProyectoIPS.XCYLSProyectoIPSDomainModel), "UPM_IPS.XCYLSProyectoIPS.GeneratedCode.DomainModelResx")]
		[DslDesign::DescriptionResource("UPM_IPS.XCYLSProyectoIPS.RelacionHasAtributoRelacioned/AtributoRelacion.Description", typeof(global::UPM_IPS.XCYLSProyectoIPS.XCYLSProyectoIPSDomainModel), "UPM_IPS.XCYLSProyectoIPS.GeneratedCode.DomainModelResx")]
		[DslModeling::DomainRole(DslModeling::DomainRoleOrder.Target, PropertyName = "Relacion", PropertyDisplayNameKey="UPM_IPS.XCYLSProyectoIPS.RelacionHasAtributoRelacioned/AtributoRelacion.PropertyDisplayName", PropagatesDelete = true,  PropagatesCopy = DslModeling::PropagatesCopyOption.DoNotPropagateCopy, Multiplicity = DslModeling::Multiplicity.One)]
		[DslModeling::DomainObjectId("91ce5276-cd6d-4d8c-998d-bb78631a61bb")]
		public virtual AtributoRelacion AtributoRelacion
		{
			[global::System.Diagnostics.DebuggerStepThrough]
			get
			{
				return (AtributoRelacion)DslModeling::DomainRoleInfo.GetRolePlayer(this, AtributoRelacionDomainRoleId);
			}
			[global::System.Diagnostics.DebuggerStepThrough]
			set
			{
				DslModeling::DomainRoleInfo.SetRolePlayer(this, AtributoRelacionDomainRoleId, value);
			}
		}
				
		#endregion
		#region Static methods to access AtributoRelacioned of a Relacion
		/// <summary>
		/// Gets a list of AtributoRelacioned.
		/// </summary>
		[global::System.Diagnostics.DebuggerStepThrough]
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1011")]
		public static DslModeling::LinkedElementCollection<AtributoRelacion> GetAtributoRelacioned(Relacion element)
		{
			return GetRoleCollection<DslModeling::LinkedElementCollection<AtributoRelacion>, AtributoRelacion>(element, RelacionDomainRoleId);
		}
		#endregion
		#region Relacion link accessor
		/// <summary>
		/// Get the list of RelacionHasAtributoRelacioned links to a Relacion.
		/// </summary>
		[global::System.Diagnostics.DebuggerStepThrough]
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1011")]
		public static global::System.Collections.ObjectModel.ReadOnlyCollection<global::UPM_IPS.XCYLSProyectoIPS.RelacionHasAtributoRelacioned> GetLinksToAtributoRelacioned ( global::UPM_IPS.XCYLSProyectoIPS.Relacion relacionInstance )
		{
			return DslModeling::DomainRoleInfo.GetElementLinks<global::UPM_IPS.XCYLSProyectoIPS.RelacionHasAtributoRelacioned>(relacionInstance, global::UPM_IPS.XCYLSProyectoIPS.RelacionHasAtributoRelacioned.RelacionDomainRoleId);
		}
		#endregion
		#region AtributoRelacion link accessor
		/// <summary>
		/// Get the RelacionHasAtributoRelacioned link to a AtributoRelacion.
		/// </summary>
		[global::System.Diagnostics.DebuggerStepThrough]
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1011")]
		public static global::UPM_IPS.XCYLSProyectoIPS.RelacionHasAtributoRelacioned GetLinkToRelacion (global::UPM_IPS.XCYLSProyectoIPS.AtributoRelacion atributoRelacionInstance)
		{
			global::System.Collections.Generic.IList<global::UPM_IPS.XCYLSProyectoIPS.RelacionHasAtributoRelacioned> links = DslModeling::DomainRoleInfo.GetElementLinks<global::UPM_IPS.XCYLSProyectoIPS.RelacionHasAtributoRelacioned>(atributoRelacionInstance, global::UPM_IPS.XCYLSProyectoIPS.RelacionHasAtributoRelacioned.AtributoRelacionDomainRoleId);
			global::System.Diagnostics.Debug.Assert(links.Count <= 1, "Multiplicity of AtributoRelacion not obeyed.");
			if ( links.Count == 0 )
			{
				return null;
			}
			else
			{
				return links[0];
			}
		}
		#endregion
		#region RelacionHasAtributoRelacioned instance accessors
		
		/// <summary>
		/// Get any RelacionHasAtributoRelacioned links between a given Relacion and a AtributoRelacion.
		/// </summary>
		[global::System.Diagnostics.DebuggerStepThrough]
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1011")]
		public static global::System.Collections.ObjectModel.ReadOnlyCollection<global::UPM_IPS.XCYLSProyectoIPS.RelacionHasAtributoRelacioned> GetLinks( global::UPM_IPS.XCYLSProyectoIPS.Relacion source, global::UPM_IPS.XCYLSProyectoIPS.AtributoRelacion target )
		{
			global::System.Collections.Generic.List<global::UPM_IPS.XCYLSProyectoIPS.RelacionHasAtributoRelacioned> outLinks = new global::System.Collections.Generic.List<global::UPM_IPS.XCYLSProyectoIPS.RelacionHasAtributoRelacioned>();
			global::System.Collections.Generic.IList<global::UPM_IPS.XCYLSProyectoIPS.RelacionHasAtributoRelacioned> links = DslModeling::DomainRoleInfo.GetElementLinks<global::UPM_IPS.XCYLSProyectoIPS.RelacionHasAtributoRelacioned>(source, global::UPM_IPS.XCYLSProyectoIPS.RelacionHasAtributoRelacioned.RelacionDomainRoleId);
			foreach ( global::UPM_IPS.XCYLSProyectoIPS.RelacionHasAtributoRelacioned link in links )
			{
				if ( target.Equals(link.AtributoRelacion) )
				{
					outLinks.Add(link);
				}
			}
			return outLinks.AsReadOnly();
		}
		/// <summary>
		/// Get the one RelacionHasAtributoRelacioned link between a given Relacionand a AtributoRelacion.
		/// </summary>
		[global::System.Diagnostics.DebuggerStepThrough]
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1011")]
		public static global::UPM_IPS.XCYLSProyectoIPS.RelacionHasAtributoRelacioned GetLink( global::UPM_IPS.XCYLSProyectoIPS.Relacion source, global::UPM_IPS.XCYLSProyectoIPS.AtributoRelacion target )
		{
			global::System.Collections.Generic.IList<global::UPM_IPS.XCYLSProyectoIPS.RelacionHasAtributoRelacioned> links = DslModeling::DomainRoleInfo.GetElementLinks<global::UPM_IPS.XCYLSProyectoIPS.RelacionHasAtributoRelacioned>(source, global::UPM_IPS.XCYLSProyectoIPS.RelacionHasAtributoRelacioned.RelacionDomainRoleId);
			foreach ( global::UPM_IPS.XCYLSProyectoIPS.RelacionHasAtributoRelacioned link in links )
			{
				if ( target.Equals(link.AtributoRelacion) )
				{
					return link;
				}
			}
			return null;
		}
		
		#endregion
	}
}
namespace UPM_IPS.XCYLSProyectoIPS
{
	/// <summary>
	/// DomainRelationship EntidadHasAtributoClaves
	/// Description for UPM_IPS.XCYLSProyectoIPS.EntidadHasAtributoClaves
	/// </summary>
	[DslDesign::DisplayNameResource("UPM_IPS.XCYLSProyectoIPS.EntidadHasAtributoClaves.DisplayName", typeof(global::UPM_IPS.XCYLSProyectoIPS.XCYLSProyectoIPSDomainModel), "UPM_IPS.XCYLSProyectoIPS.GeneratedCode.DomainModelResx")]
	[DslDesign::DescriptionResource("UPM_IPS.XCYLSProyectoIPS.EntidadHasAtributoClaves.Description", typeof(global::UPM_IPS.XCYLSProyectoIPS.XCYLSProyectoIPSDomainModel), "UPM_IPS.XCYLSProyectoIPS.GeneratedCode.DomainModelResx")]
	[DslModeling::DomainModelOwner(typeof(global::UPM_IPS.XCYLSProyectoIPS.XCYLSProyectoIPSDomainModel))]
	[global::System.CLSCompliant(true)]
	[DslModeling::DomainRelationship(IsEmbedding=true)]
	[DslModeling::DomainObjectId("fd1da951-a176-4b3f-ab49-2fb24723354a")]
	public partial class EntidadHasAtributoClaves : DslModeling::ElementLink
	{
		#region Constructors, domain class Id
		
		/// <summary>
		/// EntidadHasAtributoClaves domain class Id.
		/// </summary>
		public static readonly new global::System.Guid DomainClassId = new global::System.Guid(0xfd1da951, 0xa176, 0x4b3f, 0xab, 0x49, 0x2f, 0xb2, 0x47, 0x23, 0x35, 0x4a);
	
				
		/// <summary>
		/// Constructor
		/// Creates a EntidadHasAtributoClaves link in the same Partition as the given Entidad
		/// </summary>
		/// <param name="source">Entidad to use as the source of the relationship.</param>
		/// <param name="target">AtributoClave to use as the target of the relationship.</param>
		public EntidadHasAtributoClaves(Entidad source, AtributoClave target)
			: base((source != null ? source.Partition : null), new DslModeling::RoleAssignment[]{new DslModeling::RoleAssignment(EntidadHasAtributoClaves.EntidadDomainRoleId, source), new DslModeling::RoleAssignment(EntidadHasAtributoClaves.AtributoClaveDomainRoleId, target)}, null)
		{
		}
		
		/// <summary>
		/// Constructor
		/// </summary>
		/// <param name="store">Store where new link is to be created.</param>
		/// <param name="roleAssignments">List of relationship role assignments.</param>
		public EntidadHasAtributoClaves(DslModeling::Store store, params DslModeling::RoleAssignment[] roleAssignments)
			: base(store != null ? store.DefaultPartitionForClass(DomainClassId) : null, roleAssignments, null)
		{
		}
		
		/// <summary>
		/// Constructor
		/// </summary>
		/// <param name="store">Store where new link is to be created.</param>
		/// <param name="roleAssignments">List of relationship role assignments.</param>
		/// <param name="propertyAssignments">List of properties assignments to set on the new link.</param>
		public EntidadHasAtributoClaves(DslModeling::Store store, DslModeling::RoleAssignment[] roleAssignments, DslModeling::PropertyAssignment[] propertyAssignments)
			: base(store != null ? store.DefaultPartitionForClass(DomainClassId) : null, roleAssignments, propertyAssignments)
		{
		}
		
		/// <summary>
		/// Constructor
		/// </summary>
		/// <param name="partition">Partition where new link is to be created.</param>
		/// <param name="roleAssignments">List of relationship role assignments.</param>
		public EntidadHasAtributoClaves(DslModeling::Partition partition, params DslModeling::RoleAssignment[] roleAssignments)
			: base(partition, roleAssignments, null)
		{
		}
		
		/// <summary>
		/// Constructor
		/// </summary>
		/// <param name="partition">Partition where new link is to be created.</param>
		/// <param name="roleAssignments">List of relationship role assignments.</param>
		/// <param name="propertyAssignments">List of properties assignments to set on the new link.</param>
		public EntidadHasAtributoClaves(DslModeling::Partition partition, DslModeling::RoleAssignment[] roleAssignments, DslModeling::PropertyAssignment[] propertyAssignments)
			: base(partition, roleAssignments, propertyAssignments)
		{
		}
		#endregion
		#region Entidad domain role code
		
		/// <summary>
		/// Entidad domain role Id.
		/// </summary>
		public static readonly global::System.Guid EntidadDomainRoleId = new global::System.Guid(0x5bafca94, 0x3e1c, 0x46c7, 0xaf, 0xa7, 0xac, 0xb7, 0xcb, 0xaf, 0xd7, 0x09);
		
		/// <summary>
		/// DomainRole Entidad
		/// Description for UPM_IPS.XCYLSProyectoIPS.EntidadHasAtributoClaves.Entidad
		/// </summary>
		[DslDesign::DisplayNameResource("UPM_IPS.XCYLSProyectoIPS.EntidadHasAtributoClaves/Entidad.DisplayName", typeof(global::UPM_IPS.XCYLSProyectoIPS.XCYLSProyectoIPSDomainModel), "UPM_IPS.XCYLSProyectoIPS.GeneratedCode.DomainModelResx")]
		[DslDesign::DescriptionResource("UPM_IPS.XCYLSProyectoIPS.EntidadHasAtributoClaves/Entidad.Description", typeof(global::UPM_IPS.XCYLSProyectoIPS.XCYLSProyectoIPSDomainModel), "UPM_IPS.XCYLSProyectoIPS.GeneratedCode.DomainModelResx")]
		[DslModeling::DomainRole(DslModeling::DomainRoleOrder.Source, PropertyName = "AtributoClaves", PropertyDisplayNameKey="UPM_IPS.XCYLSProyectoIPS.EntidadHasAtributoClaves/Entidad.PropertyDisplayName",  PropagatesCopy = DslModeling::PropagatesCopyOption.PropagatesCopyToLinkAndOppositeRolePlayer, Multiplicity = DslModeling::Multiplicity.ZeroMany)]
		[DslModeling::DomainObjectId("5bafca94-3e1c-46c7-afa7-acb7cbafd709")]
		public virtual Entidad Entidad
		{
			[global::System.Diagnostics.DebuggerStepThrough]
			get
			{
				return (Entidad)DslModeling::DomainRoleInfo.GetRolePlayer(this, EntidadDomainRoleId);
			}
			[global::System.Diagnostics.DebuggerStepThrough]
			set
			{
				DslModeling::DomainRoleInfo.SetRolePlayer(this, EntidadDomainRoleId, value);
			}
		}
				
		#endregion
		#region Static methods to access Entidad of a AtributoClave
		/// <summary>
		/// Gets Entidad.
		/// </summary>
		[global::System.Diagnostics.DebuggerStepThrough]
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1011")]
		public static Entidad GetEntidad(AtributoClave element)
		{
			return DslModeling::DomainRoleInfo.GetLinkedElement(element, AtributoClaveDomainRoleId) as Entidad;
		}
		
		/// <summary>
		/// Sets Entidad.
		/// </summary>
		[global::System.Diagnostics.DebuggerStepThrough]
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1011")]
		public static void SetEntidad(AtributoClave element, Entidad newEntidad)
		{
			DslModeling::DomainRoleInfo.SetLinkedElement(element, AtributoClaveDomainRoleId, newEntidad);
		}
		#endregion
		#region AtributoClave domain role code
		
		/// <summary>
		/// AtributoClave domain role Id.
		/// </summary>
		public static readonly global::System.Guid AtributoClaveDomainRoleId = new global::System.Guid(0x3517425f, 0x99ac, 0x4a59, 0x89, 0x0e, 0x43, 0x34, 0xa5, 0xed, 0x0e, 0xd3);
		
		/// <summary>
		/// DomainRole AtributoClave
		/// Description for UPM_IPS.XCYLSProyectoIPS.EntidadHasAtributoClaves.AtributoClave
		/// </summary>
		[DslDesign::DisplayNameResource("UPM_IPS.XCYLSProyectoIPS.EntidadHasAtributoClaves/AtributoClave.DisplayName", typeof(global::UPM_IPS.XCYLSProyectoIPS.XCYLSProyectoIPSDomainModel), "UPM_IPS.XCYLSProyectoIPS.GeneratedCode.DomainModelResx")]
		[DslDesign::DescriptionResource("UPM_IPS.XCYLSProyectoIPS.EntidadHasAtributoClaves/AtributoClave.Description", typeof(global::UPM_IPS.XCYLSProyectoIPS.XCYLSProyectoIPSDomainModel), "UPM_IPS.XCYLSProyectoIPS.GeneratedCode.DomainModelResx")]
		[DslModeling::DomainRole(DslModeling::DomainRoleOrder.Target, PropertyName = "Entidad", PropertyDisplayNameKey="UPM_IPS.XCYLSProyectoIPS.EntidadHasAtributoClaves/AtributoClave.PropertyDisplayName", PropagatesDelete = true,  PropagatesCopy = DslModeling::PropagatesCopyOption.DoNotPropagateCopy, Multiplicity = DslModeling::Multiplicity.One)]
		[DslModeling::DomainObjectId("3517425f-99ac-4a59-890e-4334a5ed0ed3")]
		public virtual AtributoClave AtributoClave
		{
			[global::System.Diagnostics.DebuggerStepThrough]
			get
			{
				return (AtributoClave)DslModeling::DomainRoleInfo.GetRolePlayer(this, AtributoClaveDomainRoleId);
			}
			[global::System.Diagnostics.DebuggerStepThrough]
			set
			{
				DslModeling::DomainRoleInfo.SetRolePlayer(this, AtributoClaveDomainRoleId, value);
			}
		}
				
		#endregion
		#region Static methods to access AtributoClaves of a Entidad
		/// <summary>
		/// Gets a list of AtributoClaves.
		/// </summary>
		[global::System.Diagnostics.DebuggerStepThrough]
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1011")]
		public static DslModeling::LinkedElementCollection<AtributoClave> GetAtributoClaves(Entidad element)
		{
			return GetRoleCollection<DslModeling::LinkedElementCollection<AtributoClave>, AtributoClave>(element, EntidadDomainRoleId);
		}
		#endregion
		#region Entidad link accessor
		/// <summary>
		/// Get the list of EntidadHasAtributoClaves links to a Entidad.
		/// </summary>
		[global::System.Diagnostics.DebuggerStepThrough]
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1011")]
		public static global::System.Collections.ObjectModel.ReadOnlyCollection<global::UPM_IPS.XCYLSProyectoIPS.EntidadHasAtributoClaves> GetLinksToAtributoClaves ( global::UPM_IPS.XCYLSProyectoIPS.Entidad entidadInstance )
		{
			return DslModeling::DomainRoleInfo.GetElementLinks<global::UPM_IPS.XCYLSProyectoIPS.EntidadHasAtributoClaves>(entidadInstance, global::UPM_IPS.XCYLSProyectoIPS.EntidadHasAtributoClaves.EntidadDomainRoleId);
		}
		#endregion
		#region AtributoClave link accessor
		/// <summary>
		/// Get the EntidadHasAtributoClaves link to a AtributoClave.
		/// </summary>
		[global::System.Diagnostics.DebuggerStepThrough]
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1011")]
		public static global::UPM_IPS.XCYLSProyectoIPS.EntidadHasAtributoClaves GetLinkToEntidad (global::UPM_IPS.XCYLSProyectoIPS.AtributoClave atributoClaveInstance)
		{
			global::System.Collections.Generic.IList<global::UPM_IPS.XCYLSProyectoIPS.EntidadHasAtributoClaves> links = DslModeling::DomainRoleInfo.GetElementLinks<global::UPM_IPS.XCYLSProyectoIPS.EntidadHasAtributoClaves>(atributoClaveInstance, global::UPM_IPS.XCYLSProyectoIPS.EntidadHasAtributoClaves.AtributoClaveDomainRoleId);
			global::System.Diagnostics.Debug.Assert(links.Count <= 1, "Multiplicity of AtributoClave not obeyed.");
			if ( links.Count == 0 )
			{
				return null;
			}
			else
			{
				return links[0];
			}
		}
		#endregion
		#region EntidadHasAtributoClaves instance accessors
		
		/// <summary>
		/// Get any EntidadHasAtributoClaves links between a given Entidad and a AtributoClave.
		/// </summary>
		[global::System.Diagnostics.DebuggerStepThrough]
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1011")]
		public static global::System.Collections.ObjectModel.ReadOnlyCollection<global::UPM_IPS.XCYLSProyectoIPS.EntidadHasAtributoClaves> GetLinks( global::UPM_IPS.XCYLSProyectoIPS.Entidad source, global::UPM_IPS.XCYLSProyectoIPS.AtributoClave target )
		{
			global::System.Collections.Generic.List<global::UPM_IPS.XCYLSProyectoIPS.EntidadHasAtributoClaves> outLinks = new global::System.Collections.Generic.List<global::UPM_IPS.XCYLSProyectoIPS.EntidadHasAtributoClaves>();
			global::System.Collections.Generic.IList<global::UPM_IPS.XCYLSProyectoIPS.EntidadHasAtributoClaves> links = DslModeling::DomainRoleInfo.GetElementLinks<global::UPM_IPS.XCYLSProyectoIPS.EntidadHasAtributoClaves>(source, global::UPM_IPS.XCYLSProyectoIPS.EntidadHasAtributoClaves.EntidadDomainRoleId);
			foreach ( global::UPM_IPS.XCYLSProyectoIPS.EntidadHasAtributoClaves link in links )
			{
				if ( target.Equals(link.AtributoClave) )
				{
					outLinks.Add(link);
				}
			}
			return outLinks.AsReadOnly();
		}
		/// <summary>
		/// Get the one EntidadHasAtributoClaves link between a given Entidadand a AtributoClave.
		/// </summary>
		[global::System.Diagnostics.DebuggerStepThrough]
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1011")]
		public static global::UPM_IPS.XCYLSProyectoIPS.EntidadHasAtributoClaves GetLink( global::UPM_IPS.XCYLSProyectoIPS.Entidad source, global::UPM_IPS.XCYLSProyectoIPS.AtributoClave target )
		{
			global::System.Collections.Generic.IList<global::UPM_IPS.XCYLSProyectoIPS.EntidadHasAtributoClaves> links = DslModeling::DomainRoleInfo.GetElementLinks<global::UPM_IPS.XCYLSProyectoIPS.EntidadHasAtributoClaves>(source, global::UPM_IPS.XCYLSProyectoIPS.EntidadHasAtributoClaves.EntidadDomainRoleId);
			foreach ( global::UPM_IPS.XCYLSProyectoIPS.EntidadHasAtributoClaves link in links )
			{
				if ( target.Equals(link.AtributoClave) )
				{
					return link;
				}
			}
			return null;
		}
		
		#endregion
	}
}
