//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using DslModeling = global::Microsoft.VisualStudio.Modeling;
using DslDesign = global::Microsoft.VisualStudio.Modeling.Design;
using DslDiagrams = global::Microsoft.VisualStudio.Modeling.Diagrams;
namespace UPM_IPS.XCYLSProyectoIPS
{
	/// <summary>
	/// DomainModel XCYLSProyectoIPSDomainModel
	/// Description for UPM_IPS.XCYLSProyectoIPS.XCYLSProyectoIPS
	/// </summary>
	[DslDesign::DisplayNameResource("UPM_IPS.XCYLSProyectoIPS.XCYLSProyectoIPSDomainModel.DisplayName", typeof(global::UPM_IPS.XCYLSProyectoIPS.XCYLSProyectoIPSDomainModel), "UPM_IPS.XCYLSProyectoIPS.GeneratedCode.DomainModelResx")]
	[DslDesign::DescriptionResource("UPM_IPS.XCYLSProyectoIPS.XCYLSProyectoIPSDomainModel.Description", typeof(global::UPM_IPS.XCYLSProyectoIPS.XCYLSProyectoIPSDomainModel), "UPM_IPS.XCYLSProyectoIPS.GeneratedCode.DomainModelResx")]
	[global::System.CLSCompliant(true)]
	[DslModeling::DependsOnDomainModel(typeof(global::Microsoft.VisualStudio.Modeling.CoreDomainModel))]
	[DslModeling::DependsOnDomainModel(typeof(global::Microsoft.VisualStudio.Modeling.Diagrams.CoreDesignSurfaceDomainModel))]
	[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Maintainability", "CA1506:AvoidExcessiveClassCoupling", Justification = "Generated code.")]
	[DslModeling::DomainObjectId("4c2de3c8-9232-4a16-be74-1ea73f22a0a8")]
	public partial class XCYLSProyectoIPSDomainModel : DslModeling::DomainModel
	{
		#region Constructor, domain model Id
	
		/// <summary>
		/// XCYLSProyectoIPSDomainModel domain model Id.
		/// </summary>
		public static readonly global::System.Guid DomainModelId = new global::System.Guid(0x4c2de3c8, 0x9232, 0x4a16, 0xbe, 0x74, 0x1e, 0xa7, 0x3f, 0x22, 0xa0, 0xa8);
	
		/// <summary>
		/// Constructor.
		/// </summary>
		/// <param name="store">Store containing the domain model.</param>
		public XCYLSProyectoIPSDomainModel(DslModeling::Store store)
			: base(store, DomainModelId)
		{
			// Call the partial method to allow any required serialization setup to be done.
			this.InitializeSerialization(store);		
		}
		
	
		///<Summary>
		/// Defines a partial method that will be called from the constructor to
		/// allow any necessary serialization setup to be done.
		///</Summary>
		///<remarks>
		/// For a DSL created with the DSL Designer wizard, an implementation of this 
		/// method will be generated in the GeneratedCode\SerializationHelper.cs class.
		///</remarks>
		partial void InitializeSerialization(DslModeling::Store store);
	
	
		#endregion
		#region Domain model reflection
			
		/// <summary>
		/// Gets the list of generated domain model types (classes, rules, relationships).
		/// </summary>
		/// <returns>List of types.</returns>
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Maintainability", "CA1506:AvoidExcessiveClassCoupling", Justification = "Generated code.")]	
		protected sealed override global::System.Type[] GetGeneratedDomainModelTypes()
		{
			return new global::System.Type[]
			{
				typeof(DeraWebIPS),
				typeof(Entidad),
				typeof(Relacion),
				typeof(AtributoEntidad),
				typeof(AtributoRelacion),
				typeof(AtributoClave),
				typeof(Atributo),
				typeof(EstiloPaginaWeb),
				typeof(EstiloPortalWeb),
				typeof(EstiloCampoFormulario),
				typeof(DeraWebIPSHasEntidad),
				typeof(EntidadReferencesRelacioned),
				typeof(DeraWebIPSHasRelacioned),
				typeof(EntidadHasAtributoEntidad),
				typeof(RelacionHasAtributoRelacioned),
				typeof(EntidadHasAtributoClaves),
				typeof(RelacionReferencesEntidad1),
				typeof(DeraWebIPSHasEstiloPortalWeb),
				typeof(AtributoHasEstiloCampoFormulario),
				typeof(EntidadHasEstiloPaginaWeb),
				typeof(XCYLSProyectoIPSDiagram),
				typeof(MetaforaEnt_Rel),
				typeof(MetaforaEnt_Atr),
				typeof(MetaforaRel_Atr),
				typeof(MetaforaRel_Ent),
				typeof(EntidadShape),
				typeof(RelacionShape),
				typeof(AtributoEntShape),
				typeof(AtributoClaveShape),
				typeof(AtributoRelacionTool),
				typeof(global::UPM_IPS.XCYLSProyectoIPS.FixUpDiagram),
				typeof(global::UPM_IPS.XCYLSProyectoIPS.DecoratorPropertyChanged),
				typeof(global::UPM_IPS.XCYLSProyectoIPS.ConnectorRolePlayerChanged),
			};
		}
		/// <summary>
		/// Gets the list of generated domain properties.
		/// </summary>
		/// <returns>List of property data.</returns>
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Maintainability", "CA1506:AvoidExcessiveClassCoupling", Justification = "Generated code.")]	
		protected sealed override DomainMemberInfo[] GetGeneratedDomainProperties()
		{
			return new DomainMemberInfo[]
			{
				new DomainMemberInfo(typeof(Entidad), "Name", Entidad.NameDomainPropertyId, typeof(Entidad.NamePropertyHandler)),
				new DomainMemberInfo(typeof(Relacion), "Name", Relacion.NameDomainPropertyId, typeof(Relacion.NamePropertyHandler)),
				new DomainMemberInfo(typeof(AtributoEntidad), "Null", AtributoEntidad.NullDomainPropertyId, typeof(AtributoEntidad.NullPropertyHandler)),
				new DomainMemberInfo(typeof(AtributoEntidad), "Único", AtributoEntidad.ÚnicoDomainPropertyId, typeof(AtributoEntidad.ÚnicoPropertyHandler)),
				new DomainMemberInfo(typeof(AtributoEntidad), "Longitud", AtributoEntidad.LongitudDomainPropertyId, typeof(AtributoEntidad.LongitudPropertyHandler)),
				new DomainMemberInfo(typeof(AtributoRelacion), "Único", AtributoRelacion.ÚnicoDomainPropertyId, typeof(AtributoRelacion.ÚnicoPropertyHandler)),
				new DomainMemberInfo(typeof(AtributoRelacion), "Null", AtributoRelacion.NullDomainPropertyId, typeof(AtributoRelacion.NullPropertyHandler)),
				new DomainMemberInfo(typeof(AtributoClave), "Único", AtributoClave.ÚnicoDomainPropertyId, typeof(AtributoClave.ÚnicoPropertyHandler)),
				new DomainMemberInfo(typeof(Atributo), "Nombre", Atributo.NombreDomainPropertyId, typeof(Atributo.NombrePropertyHandler)),
				new DomainMemberInfo(typeof(Atributo), "Tipo", Atributo.TipoDomainPropertyId, typeof(Atributo.TipoPropertyHandler)),
				new DomainMemberInfo(typeof(Atributo), "Min", Atributo.MinDomainPropertyId, typeof(Atributo.MinPropertyHandler)),
				new DomainMemberInfo(typeof(Atributo), "Max", Atributo.MaxDomainPropertyId, typeof(Atributo.MaxPropertyHandler)),
				new DomainMemberInfo(typeof(Atributo), "Valores", Atributo.ValoresDomainPropertyId, typeof(Atributo.ValoresPropertyHandler)),
				new DomainMemberInfo(typeof(EstiloPaginaWeb), "ColorTexto", EstiloPaginaWeb.ColorTextoDomainPropertyId, typeof(EstiloPaginaWeb.ColorTextoPropertyHandler)),
				new DomainMemberInfo(typeof(EstiloPaginaWeb), "AlineaciónTexto", EstiloPaginaWeb.AlineaciónTextoDomainPropertyId, typeof(EstiloPaginaWeb.AlineaciónTextoPropertyHandler)),
				new DomainMemberInfo(typeof(EstiloPaginaWeb), "TipoLetra", EstiloPaginaWeb.TipoLetraDomainPropertyId, typeof(EstiloPaginaWeb.TipoLetraPropertyHandler)),
				new DomainMemberInfo(typeof(EstiloPaginaWeb), "TamañoLetra", EstiloPaginaWeb.TamañoLetraDomainPropertyId, typeof(EstiloPaginaWeb.TamañoLetraPropertyHandler)),
				new DomainMemberInfo(typeof(EstiloPortalWeb), "ColorFondo", EstiloPortalWeb.ColorFondoDomainPropertyId, typeof(EstiloPortalWeb.ColorFondoPropertyHandler)),
				new DomainMemberInfo(typeof(EstiloCampoFormulario), "Visualizacion", EstiloCampoFormulario.VisualizacionDomainPropertyId, typeof(EstiloCampoFormulario.VisualizacionPropertyHandler)),
				new DomainMemberInfo(typeof(EntidadReferencesRelacioned), "cardinaridad", EntidadReferencesRelacioned.cardinaridadDomainPropertyId, typeof(EntidadReferencesRelacioned.cardinaridadPropertyHandler)),
				new DomainMemberInfo(typeof(EntidadReferencesRelacioned), "relacionB", EntidadReferencesRelacioned.relacionBDomainPropertyId, typeof(EntidadReferencesRelacioned.relacionBPropertyHandler)),
				new DomainMemberInfo(typeof(RelacionReferencesEntidad1), "cardinalidad", RelacionReferencesEntidad1.cardinalidadDomainPropertyId, typeof(RelacionReferencesEntidad1.cardinalidadPropertyHandler)),
				new DomainMemberInfo(typeof(RelacionReferencesEntidad1), "relacionA", RelacionReferencesEntidad1.relacionADomainPropertyId, typeof(RelacionReferencesEntidad1.relacionAPropertyHandler)),
			};
		}
		/// <summary>
		/// Gets the list of generated domain roles.
		/// </summary>
		/// <returns>List of role data.</returns>
		protected sealed override DomainRolePlayerInfo[] GetGeneratedDomainRoles()
		{
			return new DomainRolePlayerInfo[]
			{
				new DomainRolePlayerInfo(typeof(DeraWebIPSHasEntidad), "DeraWebIPS", DeraWebIPSHasEntidad.DeraWebIPSDomainRoleId),
				new DomainRolePlayerInfo(typeof(DeraWebIPSHasEntidad), "Entidad", DeraWebIPSHasEntidad.EntidadDomainRoleId),
				new DomainRolePlayerInfo(typeof(EntidadReferencesRelacioned), "Entidad", EntidadReferencesRelacioned.EntidadDomainRoleId),
				new DomainRolePlayerInfo(typeof(EntidadReferencesRelacioned), "Relacion", EntidadReferencesRelacioned.RelacionDomainRoleId),
				new DomainRolePlayerInfo(typeof(DeraWebIPSHasRelacioned), "DeraWebIPS", DeraWebIPSHasRelacioned.DeraWebIPSDomainRoleId),
				new DomainRolePlayerInfo(typeof(DeraWebIPSHasRelacioned), "Relacion", DeraWebIPSHasRelacioned.RelacionDomainRoleId),
				new DomainRolePlayerInfo(typeof(EntidadHasAtributoEntidad), "Entidad", EntidadHasAtributoEntidad.EntidadDomainRoleId),
				new DomainRolePlayerInfo(typeof(EntidadHasAtributoEntidad), "AtributoEntidad", EntidadHasAtributoEntidad.AtributoEntidadDomainRoleId),
				new DomainRolePlayerInfo(typeof(RelacionHasAtributoRelacioned), "Relacion", RelacionHasAtributoRelacioned.RelacionDomainRoleId),
				new DomainRolePlayerInfo(typeof(RelacionHasAtributoRelacioned), "AtributoRelacion", RelacionHasAtributoRelacioned.AtributoRelacionDomainRoleId),
				new DomainRolePlayerInfo(typeof(EntidadHasAtributoClaves), "Entidad", EntidadHasAtributoClaves.EntidadDomainRoleId),
				new DomainRolePlayerInfo(typeof(EntidadHasAtributoClaves), "AtributoClave", EntidadHasAtributoClaves.AtributoClaveDomainRoleId),
				new DomainRolePlayerInfo(typeof(RelacionReferencesEntidad1), "Relacion", RelacionReferencesEntidad1.RelacionDomainRoleId),
				new DomainRolePlayerInfo(typeof(RelacionReferencesEntidad1), "Entidad", RelacionReferencesEntidad1.EntidadDomainRoleId),
				new DomainRolePlayerInfo(typeof(DeraWebIPSHasEstiloPortalWeb), "DeraWebIPS", DeraWebIPSHasEstiloPortalWeb.DeraWebIPSDomainRoleId),
				new DomainRolePlayerInfo(typeof(DeraWebIPSHasEstiloPortalWeb), "EstiloPortalWeb", DeraWebIPSHasEstiloPortalWeb.EstiloPortalWebDomainRoleId),
				new DomainRolePlayerInfo(typeof(AtributoHasEstiloCampoFormulario), "Atributo", AtributoHasEstiloCampoFormulario.AtributoDomainRoleId),
				new DomainRolePlayerInfo(typeof(AtributoHasEstiloCampoFormulario), "EstiloCampoFormulario", AtributoHasEstiloCampoFormulario.EstiloCampoFormularioDomainRoleId),
				new DomainRolePlayerInfo(typeof(EntidadHasEstiloPaginaWeb), "Entidad", EntidadHasEstiloPaginaWeb.EntidadDomainRoleId),
				new DomainRolePlayerInfo(typeof(EntidadHasEstiloPaginaWeb), "EstiloPaginaWeb", EntidadHasEstiloPaginaWeb.EstiloPaginaWebDomainRoleId),
			};
		}
		#endregion
		#region Factory methods
		private static global::System.Collections.Generic.Dictionary<global::System.Type, int> createElementMap;
	
		/// <summary>
		/// Creates an element of specified type.
		/// </summary>
		/// <param name="partition">Partition where element is to be created.</param>
		/// <param name="elementType">Element type which belongs to this domain model.</param>
		/// <param name="propertyAssignments">New element property assignments.</param>
		/// <returns>Created element.</returns>
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Maintainability", "CA1502:AvoidExcessiveComplexity")]
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Maintainability", "CA1506:AvoidExcessiveClassCoupling", Justification = "Generated code.")]	
		public sealed override DslModeling::ModelElement CreateElement(DslModeling::Partition partition, global::System.Type elementType, DslModeling::PropertyAssignment[] propertyAssignments)
		{
			if (elementType == null) throw new global::System.ArgumentNullException("elementType");
	
			if (createElementMap == null)
			{
				createElementMap = new global::System.Collections.Generic.Dictionary<global::System.Type, int>(20);
				createElementMap.Add(typeof(DeraWebIPS), 0);
				createElementMap.Add(typeof(Entidad), 1);
				createElementMap.Add(typeof(Relacion), 2);
				createElementMap.Add(typeof(AtributoEntidad), 3);
				createElementMap.Add(typeof(AtributoRelacion), 4);
				createElementMap.Add(typeof(AtributoClave), 5);
				createElementMap.Add(typeof(EstiloPaginaWeb), 6);
				createElementMap.Add(typeof(EstiloPortalWeb), 7);
				createElementMap.Add(typeof(EstiloCampoFormulario), 8);
				createElementMap.Add(typeof(XCYLSProyectoIPSDiagram), 9);
				createElementMap.Add(typeof(MetaforaEnt_Rel), 10);
				createElementMap.Add(typeof(MetaforaEnt_Atr), 11);
				createElementMap.Add(typeof(MetaforaRel_Atr), 12);
				createElementMap.Add(typeof(MetaforaRel_Ent), 13);
				createElementMap.Add(typeof(EntidadShape), 14);
				createElementMap.Add(typeof(RelacionShape), 15);
				createElementMap.Add(typeof(AtributoEntShape), 16);
				createElementMap.Add(typeof(AtributoClaveShape), 17);
				createElementMap.Add(typeof(AtributoRelacionTool), 18);
			}
			int index;
			if (!createElementMap.TryGetValue(elementType, out index))
			{
				// construct exception error message		
				string exceptionError = string.Format(
								global::System.Globalization.CultureInfo.CurrentCulture,
								global::UPM_IPS.XCYLSProyectoIPS.XCYLSProyectoIPSDomainModel.SingletonResourceManager.GetString("UnrecognizedElementType"),
								elementType.Name);
				throw new global::System.ArgumentException(exceptionError, "elementType");
			}
			switch (index)
			{
				case 0: return new DeraWebIPS(partition, propertyAssignments);
				case 1: return new Entidad(partition, propertyAssignments);
				case 2: return new Relacion(partition, propertyAssignments);
				case 3: return new AtributoEntidad(partition, propertyAssignments);
				case 4: return new AtributoRelacion(partition, propertyAssignments);
				case 5: return new AtributoClave(partition, propertyAssignments);
				case 6: return new EstiloPaginaWeb(partition, propertyAssignments);
				case 7: return new EstiloPortalWeb(partition, propertyAssignments);
				case 8: return new EstiloCampoFormulario(partition, propertyAssignments);
				case 9: return new XCYLSProyectoIPSDiagram(partition, propertyAssignments);
				case 10: return new MetaforaEnt_Rel(partition, propertyAssignments);
				case 11: return new MetaforaEnt_Atr(partition, propertyAssignments);
				case 12: return new MetaforaRel_Atr(partition, propertyAssignments);
				case 13: return new MetaforaRel_Ent(partition, propertyAssignments);
				case 14: return new EntidadShape(partition, propertyAssignments);
				case 15: return new RelacionShape(partition, propertyAssignments);
				case 16: return new AtributoEntShape(partition, propertyAssignments);
				case 17: return new AtributoClaveShape(partition, propertyAssignments);
				case 18: return new AtributoRelacionTool(partition, propertyAssignments);
				default: return null;
			}
		}
	
		private static global::System.Collections.Generic.Dictionary<global::System.Type, int> createElementLinkMap;
	
		/// <summary>
		/// Creates an element link of specified type.
		/// </summary>
		/// <param name="partition">Partition where element is to be created.</param>
		/// <param name="elementLinkType">Element link type which belongs to this domain model.</param>
		/// <param name="roleAssignments">List of relationship role assignments for the new link.</param>
		/// <param name="propertyAssignments">New element property assignments.</param>
		/// <returns>Created element link.</returns>
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Maintainability", "CA1502:AvoidExcessiveComplexity")]
		public sealed override DslModeling::ElementLink CreateElementLink(DslModeling::Partition partition, global::System.Type elementLinkType, DslModeling::RoleAssignment[] roleAssignments, DslModeling::PropertyAssignment[] propertyAssignments)
		{
			if (elementLinkType == null) throw new global::System.ArgumentNullException("elementLinkType");
			if (roleAssignments == null) throw new global::System.ArgumentNullException("roleAssignments");
	
			if (createElementLinkMap == null)
			{
				createElementLinkMap = new global::System.Collections.Generic.Dictionary<global::System.Type, int>(10);
				createElementLinkMap.Add(typeof(DeraWebIPSHasEntidad), 0);
				createElementLinkMap.Add(typeof(EntidadReferencesRelacioned), 1);
				createElementLinkMap.Add(typeof(DeraWebIPSHasRelacioned), 2);
				createElementLinkMap.Add(typeof(EntidadHasAtributoEntidad), 3);
				createElementLinkMap.Add(typeof(RelacionHasAtributoRelacioned), 4);
				createElementLinkMap.Add(typeof(EntidadHasAtributoClaves), 5);
				createElementLinkMap.Add(typeof(RelacionReferencesEntidad1), 6);
				createElementLinkMap.Add(typeof(DeraWebIPSHasEstiloPortalWeb), 7);
				createElementLinkMap.Add(typeof(AtributoHasEstiloCampoFormulario), 8);
				createElementLinkMap.Add(typeof(EntidadHasEstiloPaginaWeb), 9);
			}
			int index;
			if (!createElementLinkMap.TryGetValue(elementLinkType, out index))
			{
				// construct exception error message
				string exceptionError = string.Format(
								global::System.Globalization.CultureInfo.CurrentCulture,
								global::UPM_IPS.XCYLSProyectoIPS.XCYLSProyectoIPSDomainModel.SingletonResourceManager.GetString("UnrecognizedElementLinkType"),
								elementLinkType.Name);
				throw new global::System.ArgumentException(exceptionError, "elementLinkType");
			
			}
			switch (index)
			{
				case 0: return new DeraWebIPSHasEntidad(partition, roleAssignments, propertyAssignments);
				case 1: return new EntidadReferencesRelacioned(partition, roleAssignments, propertyAssignments);
				case 2: return new DeraWebIPSHasRelacioned(partition, roleAssignments, propertyAssignments);
				case 3: return new EntidadHasAtributoEntidad(partition, roleAssignments, propertyAssignments);
				case 4: return new RelacionHasAtributoRelacioned(partition, roleAssignments, propertyAssignments);
				case 5: return new EntidadHasAtributoClaves(partition, roleAssignments, propertyAssignments);
				case 6: return new RelacionReferencesEntidad1(partition, roleAssignments, propertyAssignments);
				case 7: return new DeraWebIPSHasEstiloPortalWeb(partition, roleAssignments, propertyAssignments);
				case 8: return new AtributoHasEstiloCampoFormulario(partition, roleAssignments, propertyAssignments);
				case 9: return new EntidadHasEstiloPaginaWeb(partition, roleAssignments, propertyAssignments);
				default: return null;
			}
		}
		#endregion
		#region Resource manager
		
		private static global::System.Resources.ResourceManager resourceManager;
		
		/// <summary>
		/// The base name of this model's resources.
		/// </summary>
		public const string ResourceBaseName = "UPM_IPS.XCYLSProyectoIPS.GeneratedCode.DomainModelResx";
		
		/// <summary>
		/// Gets the DomainModel's ResourceManager. If the ResourceManager does not already exist, then it is created.
		/// </summary>
		public override global::System.Resources.ResourceManager ResourceManager
		{
			[global::System.Diagnostics.DebuggerStepThrough]
			get
			{
				return XCYLSProyectoIPSDomainModel.SingletonResourceManager;
			}
		}
	
		/// <summary>
		/// Gets the Singleton ResourceManager for this domain model.
		/// </summary>
		public static global::System.Resources.ResourceManager SingletonResourceManager
		{
			[global::System.Diagnostics.DebuggerStepThrough]
			get
			{
				if (XCYLSProyectoIPSDomainModel.resourceManager == null)
				{
					XCYLSProyectoIPSDomainModel.resourceManager = new global::System.Resources.ResourceManager(ResourceBaseName, typeof(XCYLSProyectoIPSDomainModel).Assembly);
				}
				return XCYLSProyectoIPSDomainModel.resourceManager;
			}
		}
		#endregion
		#region Copy/Remove closures
		/// <summary>
		/// CopyClosure cache
		/// </summary>
		private static DslModeling::IElementVisitorFilter copyClosure;
		/// <summary>
		/// DeleteClosure cache
		/// </summary>
		private static DslModeling::IElementVisitorFilter removeClosure;
		/// <summary>
		/// Returns an IElementVisitorFilter that corresponds to the ClosureType.
		/// </summary>
		/// <param name="type">closure type</param>
		/// <param name="rootElements">collection of root elements</param>
		/// <returns>IElementVisitorFilter or null</returns>
		public override DslModeling::IElementVisitorFilter GetClosureFilter(DslModeling::ClosureType type, global::System.Collections.Generic.ICollection<DslModeling::ModelElement> rootElements)
		{
			switch (type)
			{
				case DslModeling::ClosureType.CopyClosure:
					return XCYLSProyectoIPSDomainModel.CopyClosure;
				case DslModeling::ClosureType.DeleteClosure:
					return XCYLSProyectoIPSDomainModel.DeleteClosure;
			}
			return base.GetClosureFilter(type, rootElements);
		}
		/// <summary>
		/// CopyClosure cache
		/// </summary>
		private static DslModeling::IElementVisitorFilter CopyClosure
		{
			get
			{
				// Incorporate all of the closures from the models we extend
				if (XCYLSProyectoIPSDomainModel.copyClosure == null)
				{
					DslModeling::ChainingElementVisitorFilter copyFilter = new DslModeling::ChainingElementVisitorFilter();
					copyFilter.AddFilter(new XCYLSProyectoIPSCopyClosure());
					copyFilter.AddFilter(new DslModeling::CoreCopyClosure());
					copyFilter.AddFilter(new DslDiagrams::CoreDesignSurfaceCopyClosure());
					
					XCYLSProyectoIPSDomainModel.copyClosure = copyFilter;
				}
				return XCYLSProyectoIPSDomainModel.copyClosure;
			}
		}
		/// <summary>
		/// DeleteClosure cache
		/// </summary>
		private static DslModeling::IElementVisitorFilter DeleteClosure
		{
			get
			{
				// Incorporate all of the closures from the models we extend
				if (XCYLSProyectoIPSDomainModel.removeClosure == null)
				{
					DslModeling::ChainingElementVisitorFilter removeFilter = new DslModeling::ChainingElementVisitorFilter();
					removeFilter.AddFilter(new XCYLSProyectoIPSDeleteClosure());
					removeFilter.AddFilter(new DslModeling::CoreDeleteClosure());
					removeFilter.AddFilter(new DslDiagrams::CoreDesignSurfaceDeleteClosure());
		
					XCYLSProyectoIPSDomainModel.removeClosure = removeFilter;
				}
				return XCYLSProyectoIPSDomainModel.removeClosure;
			}
		}
		#endregion
		#region Diagram rule helpers
		/// <summary>
		/// Enables rules in this domain model related to diagram fixup for the given store.
		/// If diagram data will be loaded into the store, this method should be called first to ensure
		/// that the diagram behaves properly.
		/// </summary>
		public static void EnableDiagramRules(DslModeling::Store store)
		{
			if(store == null) throw new global::System.ArgumentNullException("store");
			
			DslModeling::RuleManager ruleManager = store.RuleManager;
			ruleManager.EnableRule(typeof(global::UPM_IPS.XCYLSProyectoIPS.FixUpDiagram));
			ruleManager.EnableRule(typeof(global::UPM_IPS.XCYLSProyectoIPS.DecoratorPropertyChanged));
			ruleManager.EnableRule(typeof(global::UPM_IPS.XCYLSProyectoIPS.ConnectorRolePlayerChanged));
		}
		
		/// <summary>
		/// Disables rules in this domain model related to diagram fixup for the given store.
		/// </summary>
		public static void DisableDiagramRules(DslModeling::Store store)
		{
			if(store == null) throw new global::System.ArgumentNullException("store");
			
			DslModeling::RuleManager ruleManager = store.RuleManager;
			ruleManager.DisableRule(typeof(global::UPM_IPS.XCYLSProyectoIPS.FixUpDiagram));
			ruleManager.DisableRule(typeof(global::UPM_IPS.XCYLSProyectoIPS.DecoratorPropertyChanged));
			ruleManager.DisableRule(typeof(global::UPM_IPS.XCYLSProyectoIPS.ConnectorRolePlayerChanged));
		}
		#endregion
	}
		
	#region Copy/Remove closure classes
	/// <summary>
	/// Remove closure visitor filter
	/// </summary>
	[global::System.CLSCompliant(true)]
	public partial class XCYLSProyectoIPSDeleteClosure : XCYLSProyectoIPSDeleteClosureBase, DslModeling::IElementVisitorFilter
	{
		/// <summary>
		/// Constructor
		/// </summary>
		public XCYLSProyectoIPSDeleteClosure() : base()
		{
		}
	}
	
	/// <summary>
	/// Base class for remove closure visitor filter
	/// </summary>
	[global::System.CLSCompliant(true)]
	public partial class XCYLSProyectoIPSDeleteClosureBase : DslModeling::IElementVisitorFilter
	{
		/// <summary>
		/// DomainRoles
		/// </summary>
		private global::System.Collections.Specialized.HybridDictionary domainRoles;
		/// <summary>
		/// Constructor
		/// </summary>
		public XCYLSProyectoIPSDeleteClosureBase()
		{
			#region Initialize DomainData Table
			DomainRoles.Add(global::UPM_IPS.XCYLSProyectoIPS.DeraWebIPSHasEntidad.EntidadDomainRoleId, true);
			DomainRoles.Add(global::UPM_IPS.XCYLSProyectoIPS.DeraWebIPSHasRelacioned.RelacionDomainRoleId, true);
			DomainRoles.Add(global::UPM_IPS.XCYLSProyectoIPS.EntidadHasAtributoEntidad.AtributoEntidadDomainRoleId, true);
			DomainRoles.Add(global::UPM_IPS.XCYLSProyectoIPS.RelacionHasAtributoRelacioned.AtributoRelacionDomainRoleId, true);
			DomainRoles.Add(global::UPM_IPS.XCYLSProyectoIPS.EntidadHasAtributoClaves.AtributoClaveDomainRoleId, true);
			DomainRoles.Add(global::UPM_IPS.XCYLSProyectoIPS.DeraWebIPSHasEstiloPortalWeb.EstiloPortalWebDomainRoleId, true);
			DomainRoles.Add(global::UPM_IPS.XCYLSProyectoIPS.AtributoHasEstiloCampoFormulario.EstiloCampoFormularioDomainRoleId, true);
			DomainRoles.Add(global::UPM_IPS.XCYLSProyectoIPS.EntidadHasEstiloPaginaWeb.EstiloPaginaWebDomainRoleId, true);
			#endregion
		}
		/// <summary>
		/// Called to ask the filter if a particular relationship from a source element should be included in the traversal
		/// </summary>
		/// <param name="walker">ElementWalker that is traversing the model</param>
		/// <param name="sourceElement">Model Element playing the source role</param>
		/// <param name="sourceRoleInfo">DomainRoleInfo of the role that the source element is playing in the relationship</param>
		/// <param name="domainRelationshipInfo">DomainRelationshipInfo for the ElementLink in question</param>
		/// <param name="targetRelationship">Relationship in question</param>
		/// <returns>Yes if the relationship should be traversed</returns>
		public virtual DslModeling::VisitorFilterResult ShouldVisitRelationship(DslModeling::ElementWalker walker, DslModeling::ModelElement sourceElement, DslModeling::DomainRoleInfo sourceRoleInfo, DslModeling::DomainRelationshipInfo domainRelationshipInfo, DslModeling::ElementLink targetRelationship)
		{
			return DslModeling::VisitorFilterResult.Yes;
		}
		/// <summary>
		/// Called to ask the filter if a particular role player should be Visited during traversal
		/// </summary>
		/// <param name="walker">ElementWalker that is traversing the model</param>
		/// <param name="sourceElement">Model Element playing the source role</param>
		/// <param name="elementLink">Element Link that forms the relationship to the role player in question</param>
		/// <param name="targetDomainRole">DomainRoleInfo of the target role</param>
		/// <param name="targetRolePlayer">Model Element that plays the target role in the relationship</param>
		/// <returns></returns>
		public virtual DslModeling::VisitorFilterResult ShouldVisitRolePlayer(DslModeling::ElementWalker walker, DslModeling::ModelElement sourceElement, DslModeling::ElementLink elementLink, DslModeling::DomainRoleInfo targetDomainRole, DslModeling::ModelElement targetRolePlayer)
		{
			if (targetDomainRole == null) throw new global::System.ArgumentNullException("targetDomainRole");
			return this.DomainRoles.Contains(targetDomainRole.Id) ? DslModeling::VisitorFilterResult.Yes : DslModeling::VisitorFilterResult.DoNotCare;
		}
		/// <summary>
		/// DomainRoles
		/// </summary>
		private global::System.Collections.Specialized.HybridDictionary DomainRoles
		{
			get
			{
				if (this.domainRoles == null)
				{
					this.domainRoles = new global::System.Collections.Specialized.HybridDictionary();
				}
				return this.domainRoles;
			}
		}
	
	}
	/// <summary>
	/// Copy closure visitor filter
	/// </summary>
	[global::System.CLSCompliant(true)]
	public partial class XCYLSProyectoIPSCopyClosure : XCYLSProyectoIPSCopyClosureBase, DslModeling::IElementVisitorFilter
	{
		/// <summary>
		/// Constructor
		/// </summary>
		public XCYLSProyectoIPSCopyClosure() : base()
		{
		}
	}
	/// <summary>
	/// Base class for copy closure visitor filter
	/// </summary>
	[global::System.CLSCompliant(true)]
	public partial class XCYLSProyectoIPSCopyClosureBase : DslModeling::CopyClosureFilter, DslModeling::IElementVisitorFilter
	{
		/// <summary>
		/// Constructor
		/// </summary>
		public XCYLSProyectoIPSCopyClosureBase():base()
		{
		}
	}
	#endregion
		
}
namespace UPM_IPS.XCYLSProyectoIPS
{
	/// <summary>
	/// DomainEnumeration: tipoEnumeration
	/// Description for UPM_IPS.XCYLSProyectoIPS.tipoEnumeration
	/// </summary>
	[global::System.CLSCompliant(true)]
	public enum tipoEnumeration
	{
		/// <summary>
		/// String
		/// Description for UPM_IPS.XCYLSProyectoIPS.tipoEnumeration.String
		/// </summary>
		[DslDesign::DescriptionResource("UPM_IPS.XCYLSProyectoIPS.tipoEnumeration/String.Description", typeof(global::UPM_IPS.XCYLSProyectoIPS.XCYLSProyectoIPSDomainModel), "UPM_IPS.XCYLSProyectoIPS.GeneratedCode.DomainModelResx")]
		String = 0,
		/// <summary>
		/// Int
		/// Description for UPM_IPS.XCYLSProyectoIPS.tipoEnumeration.Int
		/// </summary>
		[DslDesign::DescriptionResource("UPM_IPS.XCYLSProyectoIPS.tipoEnumeration/Int.Description", typeof(global::UPM_IPS.XCYLSProyectoIPS.XCYLSProyectoIPSDomainModel), "UPM_IPS.XCYLSProyectoIPS.GeneratedCode.DomainModelResx")]
		Int = 1,
		/// <summary>
		/// Double
		/// Description for UPM_IPS.XCYLSProyectoIPS.tipoEnumeration.Double
		/// </summary>
		[DslDesign::DescriptionResource("UPM_IPS.XCYLSProyectoIPS.tipoEnumeration/Double.Description", typeof(global::UPM_IPS.XCYLSProyectoIPS.XCYLSProyectoIPSDomainModel), "UPM_IPS.XCYLSProyectoIPS.GeneratedCode.DomainModelResx")]
		Double = 3,
		/// <summary>
		/// DateTime
		/// Description for UPM_IPS.XCYLSProyectoIPS.tipoEnumeration.DateTime
		/// </summary>
		[DslDesign::DescriptionResource("UPM_IPS.XCYLSProyectoIPS.tipoEnumeration/DateTime.Description", typeof(global::UPM_IPS.XCYLSProyectoIPS.XCYLSProyectoIPSDomainModel), "UPM_IPS.XCYLSProyectoIPS.GeneratedCode.DomainModelResx")]
		DateTime = 4,
	}
}
namespace UPM_IPS.XCYLSProyectoIPS
{
	/// <summary>
	/// DomainEnumeration: tipoNull
	/// Description for UPM_IPS.XCYLSProyectoIPS.tipoNull
	/// </summary>
	[global::System.CLSCompliant(true)]
	public enum tipoNull
	{
		/// <summary>
		/// Null
		/// Description for UPM_IPS.XCYLSProyectoIPS.tipoNull.Null
		/// </summary>
		[DslDesign::DescriptionResource("UPM_IPS.XCYLSProyectoIPS.tipoNull/Null.Description", typeof(global::UPM_IPS.XCYLSProyectoIPS.XCYLSProyectoIPSDomainModel), "UPM_IPS.XCYLSProyectoIPS.GeneratedCode.DomainModelResx")]
		Null,
		/// <summary>
		/// Not_Null
		/// Description for UPM_IPS.XCYLSProyectoIPS.tipoNull.Not_Null
		/// </summary>
		[DslDesign::DescriptionResource("UPM_IPS.XCYLSProyectoIPS.tipoNull/Not_Null.Description", typeof(global::UPM_IPS.XCYLSProyectoIPS.XCYLSProyectoIPSDomainModel), "UPM_IPS.XCYLSProyectoIPS.GeneratedCode.DomainModelResx")]
		Not_Null,
	}
}
namespace UPM_IPS.XCYLSProyectoIPS
{
	/// <summary>
	/// DomainEnumeration: tipoÚnico
	/// Description for UPM_IPS.XCYLSProyectoIPS.tipoÚnico
	/// </summary>
	[global::System.CLSCompliant(true)]
	public enum tipoÚnico
	{
		/// <summary>
		/// Único
		/// Description for UPM_IPS.XCYLSProyectoIPS.tipoÚnico.Único
		/// </summary>
		[DslDesign::DescriptionResource("UPM_IPS.XCYLSProyectoIPS.tipoÚnico/Único.Description", typeof(global::UPM_IPS.XCYLSProyectoIPS.XCYLSProyectoIPSDomainModel), "UPM_IPS.XCYLSProyectoIPS.GeneratedCode.DomainModelResx")]
		Único,
		/// <summary>
		/// No_Único
		/// Description for UPM_IPS.XCYLSProyectoIPS.tipoÚnico.No_Único
		/// </summary>
		[DslDesign::DescriptionResource("UPM_IPS.XCYLSProyectoIPS.tipoÚnico/No_Único.Description", typeof(global::UPM_IPS.XCYLSProyectoIPS.XCYLSProyectoIPSDomainModel), "UPM_IPS.XCYLSProyectoIPS.GeneratedCode.DomainModelResx")]
		No_Único,
	}
}
namespace UPM_IPS.XCYLSProyectoIPS
{
	/// <summary>
	/// DomainEnumeration: tipoAlineacion
	/// Description for UPM_IPS.XCYLSProyectoIPS.tipoAlineacion
	/// </summary>
	[global::System.CLSCompliant(true)]
	public enum tipoAlineacion
	{
		/// <summary>
		/// Izquierda
		/// Description for UPM_IPS.XCYLSProyectoIPS.tipoAlineacion.Izquierda
		/// </summary>
		[DslDesign::DescriptionResource("UPM_IPS.XCYLSProyectoIPS.tipoAlineacion/Izquierda.Description", typeof(global::UPM_IPS.XCYLSProyectoIPS.XCYLSProyectoIPSDomainModel), "UPM_IPS.XCYLSProyectoIPS.GeneratedCode.DomainModelResx")]
		Izquierda,
		/// <summary>
		/// Derecha
		/// Description for UPM_IPS.XCYLSProyectoIPS.tipoAlineacion.Derecha
		/// </summary>
		[DslDesign::DescriptionResource("UPM_IPS.XCYLSProyectoIPS.tipoAlineacion/Derecha.Description", typeof(global::UPM_IPS.XCYLSProyectoIPS.XCYLSProyectoIPSDomainModel), "UPM_IPS.XCYLSProyectoIPS.GeneratedCode.DomainModelResx")]
		Derecha,
		/// <summary>
		/// Centralizada
		/// Description for UPM_IPS.XCYLSProyectoIPS.tipoAlineacion.Centralizada
		/// </summary>
		[DslDesign::DescriptionResource("UPM_IPS.XCYLSProyectoIPS.tipoAlineacion/Centralizada.Description", typeof(global::UPM_IPS.XCYLSProyectoIPS.XCYLSProyectoIPSDomainModel), "UPM_IPS.XCYLSProyectoIPS.GeneratedCode.DomainModelResx")]
		Centralizada,
		/// <summary>
		/// Justificada
		/// Description for UPM_IPS.XCYLSProyectoIPS.tipoAlineacion.Justificada
		/// </summary>
		[DslDesign::DescriptionResource("UPM_IPS.XCYLSProyectoIPS.tipoAlineacion/Justificada.Description", typeof(global::UPM_IPS.XCYLSProyectoIPS.XCYLSProyectoIPSDomainModel), "UPM_IPS.XCYLSProyectoIPS.GeneratedCode.DomainModelResx")]
		Justificada,
	}
}
namespace UPM_IPS.XCYLSProyectoIPS
{
	/// <summary>
	/// DomainEnumeration: tipoVisualizacionCampo
	/// Description for UPM_IPS.XCYLSProyectoIPS.tipoVisualizacionCampo
	/// </summary>
	[global::System.CLSCompliant(true)]
	public enum tipoVisualizacionCampo
	{
		/// <summary>
		/// Área_de_Texto
		/// Description for UPM_IPS.XCYLSProyectoIPS.tipoVisualizacionCampo.Área_de_Texto
		/// </summary>
		[DslDesign::DescriptionResource("UPM_IPS.XCYLSProyectoIPS.tipoVisualizacionCampo/Área_de_Texto.Description", typeof(global::UPM_IPS.XCYLSProyectoIPS.XCYLSProyectoIPSDomainModel), "UPM_IPS.XCYLSProyectoIPS.GeneratedCode.DomainModelResx")]
		Área_de_Texto,
		/// <summary>
		/// Checkbox
		/// Description for UPM_IPS.XCYLSProyectoIPS.tipoVisualizacionCampo.Checkbox
		/// </summary>
		[DslDesign::DescriptionResource("UPM_IPS.XCYLSProyectoIPS.tipoVisualizacionCampo/Checkbox.Description", typeof(global::UPM_IPS.XCYLSProyectoIPS.XCYLSProyectoIPSDomainModel), "UPM_IPS.XCYLSProyectoIPS.GeneratedCode.DomainModelResx")]
		Checkbox,
		/// <summary>
		/// Radio_button
		/// Description for UPM_IPS.XCYLSProyectoIPS.tipoVisualizacionCampo.Radio_button
		/// </summary>
		[DslDesign::DescriptionResource("UPM_IPS.XCYLSProyectoIPS.tipoVisualizacionCampo/Radio_button.Description", typeof(global::UPM_IPS.XCYLSProyectoIPS.XCYLSProyectoIPSDomainModel), "UPM_IPS.XCYLSProyectoIPS.GeneratedCode.DomainModelResx")]
		Radio_button,
		/// <summary>
		/// Lista_Desplegable
		/// Description for
		/// UPM_IPS.XCYLSProyectoIPS.tipoVisualizacionCampo.Lista_Desplegable
		/// </summary>
		[DslDesign::DescriptionResource("UPM_IPS.XCYLSProyectoIPS.tipoVisualizacionCampo/Lista_Desplegable.Description", typeof(global::UPM_IPS.XCYLSProyectoIPS.XCYLSProyectoIPSDomainModel), "UPM_IPS.XCYLSProyectoIPS.GeneratedCode.DomainModelResx")]
		Lista_Desplegable,
	}
}
namespace UPM_IPS.XCYLSProyectoIPS
{
	/// <summary>
	/// DomainEnumeration: TipoCardinalidad
	/// Description for UPM_IPS.XCYLSProyectoIPS.TipoCardinalidad
	/// </summary>
	[global::System.CLSCompliant(true)]
	public enum TipoCardinalidad
	{
		/// <summary>
		/// Min1_MaxN
		/// Description for UPM_IPS.XCYLSProyectoIPS.TipoCardinalidad.Min1_MaxN
		/// </summary>
		[DslDesign::DescriptionResource("UPM_IPS.XCYLSProyectoIPS.TipoCardinalidad/Min1_MaxN.Description", typeof(global::UPM_IPS.XCYLSProyectoIPS.XCYLSProyectoIPSDomainModel), "UPM_IPS.XCYLSProyectoIPS.GeneratedCode.DomainModelResx")]
		Min1_MaxN = 0,
		/// <summary>
		/// Min0_MaxN
		/// Description for UPM_IPS.XCYLSProyectoIPS.TipoCardinalidad.Min0_MaxN
		/// </summary>
		[DslDesign::DescriptionResource("UPM_IPS.XCYLSProyectoIPS.TipoCardinalidad/Min0_MaxN.Description", typeof(global::UPM_IPS.XCYLSProyectoIPS.XCYLSProyectoIPSDomainModel), "UPM_IPS.XCYLSProyectoIPS.GeneratedCode.DomainModelResx")]
		Min0_MaxN = 0,
		/// <summary>
		/// MinN_MaxM
		/// Description for UPM_IPS.XCYLSProyectoIPS.TipoCardinalidad.MinN_MaxM
		/// </summary>
		[DslDesign::DescriptionResource("UPM_IPS.XCYLSProyectoIPS.TipoCardinalidad/MinN_MaxM.Description", typeof(global::UPM_IPS.XCYLSProyectoIPS.XCYLSProyectoIPSDomainModel), "UPM_IPS.XCYLSProyectoIPS.GeneratedCode.DomainModelResx")]
		MinN_MaxM = 2,
		/// <summary>
		/// Min1_Max1
		/// Description for UPM_IPS.XCYLSProyectoIPS.TipoCardinalidad.Min1_Max1
		/// </summary>
		[DslDesign::DescriptionResource("UPM_IPS.XCYLSProyectoIPS.TipoCardinalidad/Min1_Max1.Description", typeof(global::UPM_IPS.XCYLSProyectoIPS.XCYLSProyectoIPSDomainModel), "UPM_IPS.XCYLSProyectoIPS.GeneratedCode.DomainModelResx")]
		Min1_Max1,
		/// <summary>
		/// Min0_Max1
		/// Description for UPM_IPS.XCYLSProyectoIPS.TipoCardinalidad.Min0_Max1
		/// </summary>
		[DslDesign::DescriptionResource("UPM_IPS.XCYLSProyectoIPS.TipoCardinalidad/Min0_Max1.Description", typeof(global::UPM_IPS.XCYLSProyectoIPS.XCYLSProyectoIPSDomainModel), "UPM_IPS.XCYLSProyectoIPS.GeneratedCode.DomainModelResx")]
		Min0_Max1,
	}
}

