//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UPM_IPS.XCYLSProyectoIPS
{
	internal static partial class Constants
	{
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
		public const string DesignerFileExtension = "XCYLS_DSLProyIPS";
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
		public const string ProductName = @"XCYLSProyectoIPS";
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
		public const string CompanyName = @"UPM_IPS";
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
		public const string ProductVersion = "1.0.0.0";

		// Menu definitions
		public static readonly global::System.ComponentModel.Design.CommandID XCYLSProyectoIPSDiagramMenu = new global::System.ComponentModel.Design.CommandID(new global::System.Guid(XCYLSProyectoIPSCommandSetId), 0x10000);
		public static readonly global::System.ComponentModel.Design.CommandID XCYLSProyectoIPSExplorerMenu = new global::System.ComponentModel.Design.CommandID(new global::System.Guid(XCYLSProyectoIPSCommandSetId), 0x10001);

		// Command definitions
		public static readonly global::System.ComponentModel.Design.CommandID ViewXCYLSProyectoIPSExplorerCommand = new global::System.ComponentModel.Design.CommandID(new global::System.Guid(XCYLSProyectoIPSCommandSetId), 0x0001);
	
		// Package identifier
		public const string XCYLSProyectoIPSPackageId = "8bf689c9-05f2-4eba-86c7-f92496a3a491";
		
		// Editor factory identifier
		public const string XCYLSProyectoIPSEditorFactoryId = "33f7fbc5-4e0d-4e5d-8427-a6f34dcc0397";
		
		public const string DefaultDiagramExtension = ".diagram";
		
		// Model explorer tool window identifier
		public const string XCYLSProyectoIPSModelExplorerToolWindowId = "6155d93a-b9dc-4c39-81d3-c41161b43253";
	}
}
//
// Constants not generated from values in DesignerDefinition.dsl are defined below
//
namespace UPM_IPS.XCYLSProyectoIPS
{
	internal static partial class Constants
	{
		// Menu identifier
		public const string XCYLSProyectoIPSCommandSetId = "006eca69-7330-44c2-a273-92ba5aae7a37";
	}
}